### ISSUE TITLE
ayuda

### ISSUE THREAD

**Issue by abelnexus** [giansalex/greenter#17]
amigo logre solucionar el problema del servidor (ni yo se como la verdad) que no me dejaba crear los xml
ahora si me los crea y realiza todo perfecto el detalle es que no puedo abrir el pdf (que ya esta creado) solo abrirlo no me deja

**Comment by abelnexus** [comment]
lo abro en otra ventana el pdf y el servidor es linux
![captura](https://user-images.githubusercontent.com/34687414/37671525-e4ba64de-2c39-11e8-89f5-43edbd24bba4.PNG)

**Comment by abelnexus** [comment]
mmmm ya vi el error el pdf esta creado pero vacia (0 kb's ) y no entiendo por que el xml si se crea con los datos correctos

**Comment by giansalex** [comment]
el problema es que necesitas el ejecutable wkthmltopdf, lo mas probable es que el servidor sea de 64bits  puedes descargarlo desde [aqui](https://github.com/h4cc/wkhtmltopdf-amd64/blob/master/bin/wkhtmltopdf-amd64), y subirlo en 'vendor/bin/' , el nombre del archivo debe ser `wkthmltopdf` , el resultado final seria:
`'vendor/bin/wkthmltopdf'`

**Comment by abelnexus** [comment]
amigo al darle dowload me bota este mensaje y no descarga nada
Loop detected on cache-mia17626-MIA: TuFMEtJVICCO9h0Zpde/N9L9b7tugV9xeSSEt9M0!MIA!cache-mia17626-MIA

**Comment by abelnexus** [comment]
es este el ejecutable amigo ?
![captura](https://user-images.githubusercontent.com/34687414/37680273-656f382c-2c51-11e8-9bd4-3b36940a1007.PNG)

**Comment by abelnexus** [comment]
descargue la version para centos7 y mi hosting es 6.9 supongo que no hay problema? ya le puse en vendor/bin/ pero parece que nada aun o falta cambiar algo ams ?
![captura](https://user-images.githubusercontent.com/34687414/37681955-2a931930-2c56-11e8-9b68-2a5b7ab2a4fe.PNG)

**Comment by abelnexus** [comment]
ya lo solucione amigo me faltaban los permisos

**Comment by giansalex** [comment]
Cierto siempre los permisos infaltables.
