### ISSUE TITLE
consuta

### ISSUE THREAD

**Issue by abelnexus** [giansalex/greenter#19]
hola amigo, estoy agregando guia de remision y los codigos no los encuentro todos
no entiendo todos los requisitos: 
$baja = new Document();
        $baja->setTipoDoc('09')
            ->setNroDoc('T001-00001');

        $rel = new Document();
        $rel->setTipoDoc('02') // Tipo: Numero de Orden de Entrega
        ->setNroDoc('213123');

        $transp = new Transportist();
        $transp->setTipoDoc('6')
            ->setNumDoc('20000000002')
            ->setRznSocial('TRANSPORTES S.A.C')
            ->setPlaca('ABI-453')
            ->setChoferTipoDoc('1')
            ->setChoferDoc('40003344');

        $envio = new Shipment();
        $envio->setModTraslado('01')
            ->setCodTraslado('01')
            ->setDesTraslado('VENTA')
            ->setFecTraslado(new \DateTime())
            ->setCodPuerto('123')
            ->setIndTransbordo(false)
            ->setPesoTotal(12.5)
            ->setUndPesoTotal('KGM')
            ->setNumBultos(2)
            ->setNumContenedor('XD-2232')
            ->setLlegada(new Direction('150101', 'AV LIMA'))
            ->setPartida(new Direction('150203', 'AV ITALIA'))
            ->setTransportista($transp);

        $despatch = new Despatch();
        $despatch->setTipoDoc('09')
            ->setSerie('T001')
            ->setCorrelativo('123')
            ->setFechaEmision(new \DateTime())
            ->setCompany($this->getCompany())
            ->setDestinatario($this->getClient())
            ->setTercero((new Client())
                ->setTipoDoc('6')
                ->setNumDoc('20000000003')
                ->setRznSocial('GREENTER SA'))
            ->setObservacion('NOTA GUIA')
            ->setDocBaja($baja)
            ->setRelDoc($rel)
            ->setEnvio($envio);

        $detail = new DespatchDetail();
        $detail->setCantidad(2)
            ->setUnidad('ZZ')
            ->setDescripcion('PROD 1')
            ->setCodigo('PROD1')
            ->setCodProdSunat('P001');

        $items = $this->getItems($detail, 4);
        $despatch->setDetails($items);

**Comment by abelnexus** [comment]
$rel = new Document();
    $rel->setTipoDoc('02') // Tipo: Numero de Orden de Entrega
    ->setNroDoc('213123');
setModTraslado('01')
        ->setCodTraslado('01')
        ->setDesTraslado('VENTA')
        ->setFecTraslado(new \DateTime())
        ->setCodPuerto('123')
        ->setIndTransbordo(false)
        ->setPesoTotal(12.5)
        ->setUndPesoTotal('KGM')

estos atributos no encuentro en el anexo de sunat

**Comment by giansalex** [comment]
Este es el anexo que contiene la referencia a la Guía de Remisión
http://www.sunat.gob.pe/legislacion/superin/2017/anexoXII-117-2017.pdf

> Alli tambien indica el numero de catálogo que sea necesario

**Comment by abelnexus** [comment]
gracias, deseo modificar bastante el reporte y me esta siendo myy complicado hacerlo desde la carpeta cache , no hay otra forma de cambiar el aspecto del reporte amigo ?

**Comment by giansalex** [comment]
desde el cache no debes hacerlo ya que eso se genera automáticamente. Puedes crear una carpeta llamada `plantillas` y copias el archivo `invoice.html.twig`  desde [aquí](https://github.com/giansalex/greenter-report/blob/master/src/Report/Templates/invoice.html.twig) luego lo registras en esta [linea](https://github.com/giansalex/greenter-sample/blob/ef862b9bf470b94431029358879ea560b9db5d6f/src/Util.php#L76), quedaria asi:

```php
$html = new HtmlReport(__DIR__.'/plantillas', [
            'cache' => __DIR__ . '/../cache',
            'strict_variables' => true,
}]);
```

**Comment by abelnexus** [comment]
entonces lo que debo modificar es invoice.html.twig  y se generara el cache en base a ese ?

**Comment by giansalex** [comment]
asi es.

**Comment by abelnexus** [comment]
me vota error y solo se genera la carpeta "c9" en cache 
![captura](https://user-images.githubusercontent.com/34687414/38214905-a6bbd0d0-368b-11e8-9bf9-7b1ef5eca7a0.PNG)

$html = new HtmlReport(__DIR__.'/plantillas', [
            'cache' => __DIR__ . '/../cache',
            'strict_variables' => true,
        ]);

**Comment by abelnexus** [comment]
ahh era asi

$html = new HtmlReport(__DIR__.'/../plantillas', [
            'cache' => __DIR__ . '/../cache',
            'strict_variables' => true,
        ]);

**Comment by giansalex** [comment]
Dependia de la ruta con respecto a `src/`
