### ISSUE TITLE
consulta

### ISSUE THREAD

**Issue by abelnexus** [giansalex/greenter#21]
hola amigo, mi consulta es sobre ubigeo y dirección en la guia de remisión

->setLlegada(new Direction('150101', 'AV LIMA'))
->setPartida(new Direction('150203', 'AV ITALIA'))

aca entiendo que al poner la dirección el ubigeo debe generarse de acuerdo a la direccion ingresada
hay alguna manera de automatizar esto y que al poner o seleccionar la direccion(departamento,provincia,distrito) te vote el ubigeo exacto automaticamente}

**Comment by giansalex** [comment]
Es solo concaternar los 3 códigos: Departamento-Provincia-Distrito

**Comment by abelnexus** [comment]
con 3 select y mysql ?

**Comment by giansalex** [comment]
si claro, primero listas los departamentos, luego cuando cambie lista sus provincias y por ultimo cuando cambie provincia liste sus distritos, finalmente unes los codigos seleccionados

**Comment by abelnexus** [comment]
hola amigo ya pude hacerlo, ahora me piden que agregue guia de remision transportista y no veo ejemplos de eso

**Comment by giansalex** [comment]
agregar guia remision como comprobante (guia de remision electronica) o como un adjunto en factura.
```php
$guia = (new Document())
->setTipoDoc('31') // código guia transportista
->setNroDoc('0001-23');

$invoice->setGuias([$guia]);
```

**Comment by abelnexus** [comment]
no estoy entendiendo, el que hice es guia de remision remitente(o eso creo XD) y pra transportista solo cambia el tipo y nro de documento ?

**Comment by giansalex** [comment]
si se trata de referencia en una factura, asi es.

**Comment by abelnexus** [comment]
me dice nombre zip incorrecto creo estoy haciendo mal ya que guia de remison remitente y guia de remision transportista tiene diferentes datos

**Comment by abelnexus** [comment]
esto es lo unico que encuentro de trnasportista 

->setGuiaEmbebida((new EmbededDespatch())
                ->setLlegada(new Direction('070101', 'AV. REPUBLICA DE ARGENTINA N? 2976 URB.'))
                ->setPartida(new Direction('070101', 'AV OSCAR R BENAVIDES No 5915  PE'))
                ->setTransportista((new Client())
                    ->setTipoDoc('6')
                    ->setNumDoc('20100006376')
                    ->setRznSocial('TRANS SAC')
                )->setNroLicencia('1111111111')
                ->setTranspPlaca('B9Y-778')
                ->setTranspCodeAuth('112121')
                ->setTranspMarca('Scania')
                ->setModTraslado('01')
                ->setUndPesoBruto('KGM')
                ->setPesoBruto(2020.23)

pero eso se genera en una factura

**Comment by giansalex** [comment]
eso es cuando no quieres realizar una guia electronica por separado, entonces puedes tener una factura-guia como se le conoce, el formato del documento no cambia si es transportista o remitente.

**Comment by abelnexus** [comment]
con esto hago la guia de remision remitente y quiero hacer hacer una guia de transportista por separado que cosas cambio y agrego amigo para que cree el transportista

$transp = new Transportist();
                         $transp->setTipoDoc($_POST['Ttipo_documento'])
                         ->setNumDoc($_POST['Tdocumento'])
                         ->setRznSocial($_POST['Tdenominacion'])
                         ->setPlaca($_POST['Tplaca'])
                         ->setChoferTipoDoc($_POST['Tchofer_tipo'])
                         ->setChoferDoc($_POST['Tchofer_doc']);
                         
                         $envio = new Shipment();
                         $envio->setModTraslado($_POST['modalidad'])
                         ->setCodTraslado($_POST['motivo'])
                         ->setDesTraslado($descr)
                         ->setFecTraslado(new \DateTime())
                         ->setPesoTotal($_POST['peso'])
                         ->setUndPesoTotal($_POST['medida'])
                         ->setNumBultos($_POST['bultos'])
                         ->setNumContenedor($_POST['contenedor'])
                         ->setLlegada(new Direction($_POST['codigoubigeo2'], $_POST['llegada']))
                         ->setPartida(new Direction($_POST['codigoubigeo1'], $_POST['partida']))
                         ->setTransportista($transp);
                         
                         $despatch = new Despatch();
                         $despatch->setTipoDoc($_POST['codigodocumento'])
                         ->setSerie($_POST['serie'])
                         ->setCorrelativo($_POST['numero'])
                         ->setFechaEmision(new \DateTime())
                         ->setCompany($company)
                         ->setDestinatario($client)                         
                         ->setObservacion($_POST['observacion'])
                         ->setEnvio($envio);
                                                                                                
                          $despatch->setDetails($itemsdes);

**Comment by abelnexus** [comment]
![captura](https://user-images.githubusercontent.com/34687414/38567916-f0f9b906-3cac-11e8-81ad-7960a3e86562.PNG)

**Comment by giansalex** [comment]
según este [apartado](http://orientacion.sunat.gob.pe/index.php/empresas-menu/comprobantes-de-pago-empresas/comprobantes-de-pago-electronicos-empresas/see-desde-los-sistemas-del-contribuyente/2-comprobantes-que-se-pueden-emitir-desde-see-sistemas-del-contribuyente/guia-de-remision-electronica-modelo-general-desde-see-del-contribuyente)  el modelo se usa para remitente o transportista, la principal diferencia es el tipo de documento. Otra información que necesites agregar es algo que desconozco, tendrías que ver como es una guia fisica y que información difiere entre Remitente o transportista, pero ambos se utilizan el mismo formato.

**Comment by abelnexus** [comment]
lo decia por que vi un video donde generan una factura desde sunat sol (es lo unico que encontre ) y ponen marca de modelo de carro y es esto(justamente los datos que no uso en guia de remitente)

setNroLicencia('1111111111')
setTranspCodeAuth('112121')
setNroLicencia('1111111111')

solo agrego estos campos y sigo usando la serie "T001" ?

**Comment by giansalex** [comment]
esos campos son para factura-guia , la serie sigue siendo de la factura, el T001 seria si es una guia electronica.

**Comment by abelnexus** [comment]
ahh ya amigo ya entiendo mejor, solo cambie el tipo de documento 
      $despatch = new Despatch();
                         $despatch->setTipoDoc($_POST['codigodocumento']) cambiado a "31"
                         ->setSerie($_POST['serie']) = "T001"
                         ->setCorrelativo($_POST['numero']) "000001"

Y ME VOTA ERROR - El valor del tipo de guía es inválido. :(

**Comment by giansalex** [comment]
Al parecer solo acepta guia remitente, en su pagina no hay guia para transportista solo esta la opcion por el portal de Sunat. Tendrias que llamar a sunat y preguntarle si es posible enviar desde el sistema del contribuyente y que opcion se usaría.

![image](https://user-images.githubusercontent.com/14926587/38573356-718927d8-3cbb-11e8-93ca-ddc20dea01e5.png)

**Comment by abelnexus** [comment]
vale, si no se puede no se puede muchas gracias amigo por tu tiempo :D

**Comment by abelnexus** [comment]
amigo ese facturadorti que esta en c# que le falta ? quiero usar como base para aprender a hacer las facturas en C#

**Comment by giansalex** [comment]
ese proyecto realmente no esta pensado para ser opensource, puedes usarlo como referencia en algunos puntos como generar el xml, firmarlo o conectarte al webservice.
