### ISSUE TITLE
Error `store:///notfound` en beta

### ISSUE THREAD

**Issue by ejosvp** [giansalex/greenter#22]
Hola, estoy obteniendo el siguiente error en beta, alguna idea de por qué?

```
  +"faultstring": " - Detalle: Error opening URL 'store:///notfound'"
  +"faultcode": "soap-env:Server.200"
```

Gracias!

**Comment by giansalex** [comment]
Ya se me ha presentado ese error, es problema del servicio de SUNAT, solo esta ocurriendo con el servicio de facturas (incluye resumen diario y comunicación de bajas).
```
object(Greenter\Model\Response\Error)#191 (2) { ["code":protected]=> string(3) "200" ["message":protected]=> string(49) " - Detalle: Error opening URL 'store:///notfound'" }
Time: 00:00:00:603
```

**Comment by giansalex** [comment]
A día de hoy ese problema ya ha sido solucionado por Sunat, en futuros sucesos solo queda esperar.
