### ISSUE TITLE
UBL 2.1

### ISSUE THREAD

**Issue by juanxodj** [giansalex/greenter#23]
¿Tienes pensado incorporar la versión UBL 2.1 en los comprobantes?

**Comment by giansalex** [comment]
Si, he estado analizando desde el año pasado esta versión, realice algunas cosas en las [ramas ubl2.1](https://github.com/giansalex/greenter-xml/tree/ubl21/), lo deje por lo inestable de la documentación, actualmente algunas cosas han cambiado, inclusive la documentación oficial de SUNAT para Factura `UBL2.1` ya no es válido en varias partes. Ahora al parecer es el [excel](http://cpe.sunat.gob.pe/operador-de-servicios-electronicos-ose) de validaciones el que tiene los lineamientos a seguir, y ya que segun sunat sera obligatorio el `UBL2.1` apartir del siguiente semestre, he hecho algunas [pruebas](https://gist.github.com/giansalex/53d3b6dadb5305ee95928a854ee3abc4), es mas extenso que el `UBL 2.0`, de modo que la actualización inicial no soportara todas las características que actualmente tiene (`excluidos`: Anticipo, Detracción, Factura Guia, Factura con Percepción).

**Comment by kennyhorna** [comment]
Hola @giansalex por cierto gran librería! Alguna novedad respecto `UBL2.1`?

**Comment by juanxodj** [comment]
He integrado greenter con mi sistema de inventarios y de verdad, ni bien
tenga clientes no dudaré en hacerte su respectiva donación ;)

**Comment by HansCordovaGoicochea** [comment]
Que tal quisiera saber como puedo integrar la librería por favor gracias saludos.

**Comment by abelnexus** [comment]
que es lo que no puedes ? la libreria esta lista para que le ingreses tus datos y genera automaticamente el archivo xml -> lo empaqueta -> lo envia a sunat y obtienes el cdr y genera el reporte grafico.
prueba greenter-samples ahi hay ejemplos de los comprobantes electrónicos

**Comment by AnthonyLJ96** [comment]
Buenas tardes @giansalex , qué novedades hay con la versión 2.1 ?, el personal de SUNAT me informa que  para las nuevas que quieren iniciar a emitir boletas y facturas electrónicas es necesario que empiecen con dicha versión

**Comment by giansalex** [comment]
La próxima semana podré sacar la nueva version

**Comment by AnthonyLJ96** [comment]
@giansalex , gracias!!, sin duda alguna haré mi contribución :D

**Comment by devrodmen** [comment]
Excelente librería, pero desde hoy me pide que actualice a UBL 2.1

**Comment by devrodmen** [comment]
Amigo y podrás actualizar la librería a la V2.1 de UBL o tendrá algún costo?

**Comment by giansalex** [comment]
No es tan fácil como cambiar un código, se tiene que implementar nuevos cambios, información adicional que requiere sunat, cambios en el esquema del XML; espero esta semana poder sacar la nueva versión.

**Comment by llandresll** [comment]
Warning: require(D:\XAMPP\htdocs\greenter-sample\examples/../vendor/autoload.php): failed to open stream: No such file or directory in D:\XAMPP\htdocs\greenter-sample\examples\factura-percepcion.php on line 9

esto que quiere decir?

**Comment by AnthonyLJ** [comment]
Has instalado las dependencias con composer?
