### ISSUE TITLE
Anular Boletas

### ISSUE THREAD

**Issue by abelnexus** [giansalex/greenter#24]
Hola amigo :D , sunat no deja dar de baja boletas de venta ni notas de credito y debito que tengan serie "B001" eso tiene que ver con la version de UBL ?

**Comment by abelnexus** [comment]
string(61) "DocumentTypeCode - El valor del tipo de documento es invalido" }

**Comment by giansalex** [comment]
Los boletas se dan de baja en el resumen, es asi como lo estas enviendo (en un resumen diario de boletas)

**Comment by abelnexus** [comment]
lo estoy dando o queriedo dar de baja cada documento como en las facturas

**Comment by abelnexus** [comment]
public function getVoided()
    {
        $detial1 = new VoidedDetail();
        $detial1->setTipoDoc('01')
            ->setSerie('F001')
            ->setCorrelativo('02132132')
            ->setDesMotivoBaja('ERROR DE SISTEMA');

        $detial2 = new VoidedDetail();
        $detial2->setTipoDoc('07')
            ->setSerie('FC01')
            ->setCorrelativo('222')
            ->setDesMotivoBaja('ERROR DE RUC');

        $detial3 = new VoidedDetail();
        $detial3->setTipoDoc('03')
            ->setSerie('B001')
            ->setCorrelativo('22')
            ->setDesMotivoBaja('ERROR DE RUC');

        $voided = new Voided();
        $voided->setCorrelativo('00111')
            ->setFecComunicacion(new \DateTime())
            ->setFecGeneracion(new \DateTime())
            ->setCompany($this->getCompany())
            ->setDetails([$detial1, $detial2, $detial3]);

        return $voided;

**Comment by giansalex** [comment]
Actualmente ya no es válido, se tiene que enviar en el resumen diario de boletas, del dia en que se da de baja, con Status=3
