### ISSUE TITLE
Error en producción Bad Gateway

### ISSUE THREAD

**Issue by thefantas** [giansalex/greenter#25]
> object(Greenter\Model\Response\Error)#121 (2) {
>   ["code":protected]=>
>   string(4) "HTTP"
>   ["message":protected]=>
>   string(11) "Bad Gateway"
> }

He probado en modo beta funciona bien, pero al mandar en modo producción me manda ese error, añadí una excepción en el firewall con las dns de sunat pero de 10 intentos 4 fallan.

De hecho cuando abro en el navegador la url..  aparece esto con error 500

> An error occurred.
> 
> Sorry, the page you are looking for is currently unavailable.
> Please try again later.
> 
> If you are the system administrator of this resource then you should check the error log for details.
> 
> Faithfully yours, nginx.

https://e-factura.sunat.gob.pe/ol-ti-itcpfegem/billService?wsdl

En conclusión subir los comprobantes en tiempo real no es recomendable?

**Comment by giansalex** [comment]
Hola @thefantas , como indica @Gildus ese error se produce generalmente por saturación, esperemos que esto no ocurra cuando se usen los servicios de los  `OSE`.

**Comment by thefantas** [comment]
por lo pronto le hice un bucle de 5 intentos cada segundo.. y con eso casi garantizo  que alguno no será error 500

**Comment by giansalex** [comment]
debido a que no es un problema de esta librería, sera cerrado.
