### ISSUE TITLE
Comunicación de baja

### ISSUE THREAD

**Issue by emw3** [giansalex/greenter#26]
He revisado la documentación disponible de SUNAT acerca de la facturación electronica, pero no encuentra información detallada acerca de la comunicación de baja.
¿Cuál sería la manera correcta para anular una factura? ¿Mediante la comunicación de baja o nota de crédito?
O en qué escenarios se utiliza cada uno de esos documentos.

**Comment by giansalex** [comment]
Ambas son válidas, por ejemplo para los que emiten por el Portal de Sunat, solo tienen la opción de poder anular mediante una nota de crédito, desde el sistema del emisor puedes usar la comunicación de baja y tendrias que emitir otra factura, y los casos de uso es cuando enviaste a Sunat, pero no al cliente, si envias al cliente es mas factible por nota de crédito.
