### ISSUE TITLE
Nro. R.I. Emisor

### ISSUE THREAD

**Issue by emw3** [giansalex/greenter#27]
Como obtengo el Nro. R.I. Emisor?

**Comment by giansalex** [comment]
Se obtiene cuando se supera el proceso de homologación, pero actualmente esto ya no es obligatorio.

**Comment by emw3** [comment]
Gracias, una última duda, ya no es obligatorio mostrarlo en el PDF?

**Comment by giansalex** [comment]
Si, no seria obligatorio dado que la emisor no contaría con la resolución
