### ISSUE TITLE
los métodos setIgv() y setMtoPrecioUnitario() cómo se usan?

### ISSUE THREAD

**Issue by AnthonyLJ96** [giansalex/greenter#28]
el igv que se manda es el monto igv por cada item???, en tus ejemplos siempre pones 18.00, es un valor fijo entonces?. No encuentro el valor del monto precio unitario descrito en la documentación, como se utiliza eso??

**Comment by giansalex** [comment]
Hola @AnthonyLJ96 , 
`setIgv()` : es el Igv del item
`setMtoPrecioUnitario()`: Es el valor unitario + Igv

**Comment by AnthonyLJ96** [comment]
Hola @giansalex , gracias!
