### ISSUE TITLE
No se pudo procesar su solicitud. (Ocurrio un error en el batch) - Detalle: xxx.xxx.xxx value='ticket:  error: Elservidor remoto no se encuentra activo (codigo: 0200)

### ISSUE THREAD

**Issue by AnthonyLJ96** [giansalex/greenter#29]
Buenas tardes @giansalex , 
Cada vez que intento darle de baja a una factura o boleta me da el siguiente error:

No se pudo procesar su solicitud. (Ocurrio un error en el batch) - Detalle: xxx.xxx.xxx value='ticket:  error: Elservidor remoto no se encuentra activo (codigo: 0200)

A qué se puede deber?, estoy haciendo practicamente lo mismo que en tu repo con los ejemplos.
Saludos.

**Comment by giansalex** [comment]
Hola @AnthonyLJ96 , imagino que es en el ambiente de Producción, es un error de Sunat, ha pasado varias veces, lo único que queda es esperar y seguir intentando.

Justo ahora hay una notificacion en la pagina de sunat 
![image](https://user-images.githubusercontent.com/14926587/45328081-d8c1e700-b51f-11e8-8393-9ad1c98b338f.png)

**Comment by AnthonyLJ96** [comment]
Gracias @giansalex . Otra pregunta, para anular boletas se hace de la misma forma de las facturas?, estoy recibiendo un error con las boletas, con las facturas ya está todo ok.

El error es el siguiente:
DocumentTypeCode - El valor del tipo de documento es invalido - Detalle: xxx.xxx.xxx value='ticket: 1536620478243 error: Error en la linea:1. : 2308 (nodo: "sac:VoidedDocumentsLine/cbc:DocumentTypeCode" valor: "03")

**Comment by giansalex** [comment]
No las boletas se envían por *Resumen Diario*. 
Podrías crear otro issue si necesitas mas información.
