### ISSUE TITLE
Creación y anulación de Boletas

### ISSUE THREAD

**Issue by AnthonyLJ96** [giansalex/greenter#31]
Buenas tardes @giansalex ,
¿cómo debo hacer con las boletas ?, ¿se deberían registrar siempre como resument diario?, ¿si las hago de formas síncrona se pueden anular?. Gracias de antemano.

**Comment by giansalex** [comment]
Según la norma actual de SUNAT, las boletas solo se deben enviar en Resumen Diario tanto como para informar como para anular

**Comment by AnthonyLJ96** [comment]
A ya gracias!. ¿Y como se envía una boleta marcándola como anulada?.

**Comment by giansalex** [comment]
existe el campo `SummaryDetail::setEstado('3')`,  el numero 3 indica que es para dar de baja, otros codigos en la imagen
![image](https://user-images.githubusercontent.com/14926587/45573117-221c7a00-b831-11e8-87df-2f2452691d4e.png)

**Comment by AnthonyLJ96** [comment]
¿Entonces como se debe hacer?, es decir, ¿solo debo mandar boletas al en el resumen del día y no al momento de generarlas como es el caso de las facturas?. Por otro lado, en el caso de las boletas, ¿no se detallan los productos o servicios que se están vendiendo?.

**Comment by giansalex** [comment]
Se envían al final del dia o hasta 7 dias después, el resumen diario es de las boletas en un dia en especifico, tambien se incluye las boletas que hayan sido dadas de baja ese dia.
> No se envía información del detalle de la venta.

**Comment by AnthonyLJ96** [comment]
Ok, entonces las boletas solo se deberían enviar por el resumen diario, mientras que las facturas deberían ser enviadas al momento de generarlas (sícronas).

**Comment by giansalex** [comment]
Las facturas se envían individualmente, puedes enviarla hasta un máximo de 7 dias despues de emitirlas, pero lo recomendable es lo mas antes posible.

**Comment by AnthonyLJ96** [comment]
Está bien, gracias. En los ejemplos que subiste para el resumen diario, envías un correlativo para el documento, ¿Esto es necesario?, porque en la documentación de sunat, no encuentro esa parte y veo que lo usas para concatenarlo con la fecha.

![selection_142](https://user-images.githubusercontent.com/32845362/45588431-42ecda00-b8da-11e8-9bcc-87650775ca2a.png)

![image](https://user-images.githubusercontent.com/32845362/45588440-5e57e500-b8da-11e8-82a6-9dbf99c4f763.png)

¿Me explicarías eso por favor?.
Gracias de antemano.

**Comment by giansalex** [comment]
Lamento informarte que muchas cosas en documentación de SUNAT están erradas, como la imagen que muestras del **Identificador del resumen**, si revisas en los ejemplos de ese mismo pdf, veras que siempre hay un numero después de la fecha. Te recomendaria que revisar el excel de validaciones que se encuentra en [esta pagina](http://cpe.sunat.gob.pe/operador-de-servicios-electronicos-ose), es mas confiable y se actualiza con mas frecuencia.
![image](https://user-images.githubusercontent.com/14926587/45590885-17cdaf00-b909-11e8-86e2-2d8068b75452.png)
> En algun momento tuve la iniciativa de migrar la documentación de Sunat a Github Pages, con la finalidad de tenerla actualizada y corregir los errores que puedan tener, el repositorio era este https://github.com/giansalex/sunat-docs

**Comment by AnthonyLJ96** [comment]
Gracias @giansalex , otra consulta, ¿Después de cuánto tiempo se debe consultar a sunat si el resumen de boletas ha sido procesado correctamente?

**Comment by giansalex** [comment]
Sunat no lo indica, pero en la practica toma algunos segundos.

**Comment by byJuanjo** [comment]
Hermano, buenas tardes eh anulado una boleta y la quiero pasar en el resumen diario, junto con su nota de credito, pero me sale el siguiente error:

![captura de pantalla 2019-02-28 a la s 16 12 18](https://user-images.githubusercontent.com/21320001/53598902-ec1b4a00-3b73-11e9-98d2-6c12a20cd983.png)


Aqui pongo el json que estoy generando para dicha tarea:

`#details: array:3 [
    0 => SummaryDetail {#1101
      -tipoDoc: "03"
      -serieNro: "B001-10"
      -clienteTipo: "1"
      -clienteNro: "08791464"
      -docReferencia: null
      -percepcion: null
      -estado: "1"
      -total: "1067.80"
      -mtoOperGravadas: "904.92"
      -mtoOperInafectas: null
      -mtoOperExoneradas: null
      -mtoOperExportacion: null
      -mtoOperGratuitas: null
      -mtoOtrosCargos: null
      -mtoIGV: "162.88"
      -mtoIvap: null
      -mtoISC: null
      -mtoOtrosTributos: null
    }
    1 => SummaryDetail {#1106
      -tipoDoc: "03"
      -serieNro: "B001-11"
      -clienteTipo: "1"
      -clienteNro: "09272916"
      -docReferencia: null
      -percepcion: null
      -estado: "3"
      -total: "1067.80"
      -mtoOperGravadas: "904.92"
      -mtoOperInafectas: null
      -mtoOperExoneradas: null
      -mtoOperExportacion: null
      -mtoOperGratuitas: null
      -mtoOtrosCargos: null
      -mtoIGV: "162.88"
      -mtoIvap: null
      -mtoISC: null
      -mtoOtrosTributos: null
    }
    2 => SummaryDetail {#1104
      -tipoDoc: "07"
      -serieNro: "FF01-6"
      -clienteTipo: "1"
      -clienteNro: "09272916"
      -docReferencia: Document {#1096
        -tipoDoc: "03"
        -nroDoc: "B001-11"
      }
      -percepcion: null
      -estado: "1"
      -total: "1067.80"
      -mtoOperGravadas: "904.92"
      -mtoOperInafectas: null
      -mtoOperExoneradas: null
      -mtoOperExportacion: null
      -mtoOperGratuitas: null
      -mtoOtrosCargos: null
      -mtoIGV: "162.88"
      -mtoIvap: null
      -mtoISC: null
      -mtoOtrosTributos: null
    }
  ]`

**Comment by giansalex** [comment]
Las boletas y sus notas de crédito/debito deben tener una serie que empiece con **B**, la F es para facturas

**Comment by yaircaballero10** [comment]
No e enviado el resumen desde hace mas de 13 dias, que ago ¿?
enviar el resumen es obligatorio ¿?
tengo que hacer eso para boletas enviadas y procesadas por sunat ¿?
como le doy de baja ¿?
tengo que hacer nota de credito para cancelar la boleta o lo puedo hacer directamente dandole de baja ¿?.
