### ISSUE TITLE
El comprobante fue registrado previamente con otros datos - ERROR EN PRODUCCION 

### ISSUE THREAD

**Issue by itamaradin15** [giansalex/greenter#35]
Hola, he tenido problemas con este error  "El comprobante fue registrado previamente con otros datos"   en produccion cuando verifico en el menu sol efectivamente el documento acaba de ser generado y cuando reviso los archivos zip tambien esta el nuevo zip de ese documento.

**Comment by giansalex** [comment]
Ese mensaje sale cuando se envía el mismo comprobante repetidas veces (por ejemplo), pero eso escapa de lo que hace la libreria.

**Comment by giansalex** [comment]
Asi es, cuando se obtiene un cdr de sunat sea con estado de rechazado o aceptado, el correlativo ya no se puede usar.
