### ISSUE TITLE
Error al enviar factura sin nombre comercial: Código de error 1037

### ISSUE THREAD

**Issue by AnthonyLJ96** [giansalex/greenter#36]
Al momento de generar el xml y enviarlo me da este error:
`El XML no contiene el tag o no existe informacion de RegistrationName del emisor del documento - Detalle: xxx.xxx.xxx value='ticket: 1539991936365 error: INFO: 1037 (nodo: "cac:PartyLegalEntity/cbc:RegistrationName" valor: "")`'

He revisado el xml generado y al parece donde debería ir la razón social está imprimiendo el nombre comercial, tal vez me equivoque

**Comment by giansalex** [comment]
Me había guiado por en ese punto del SFS, pero revisando el excel y XSL  de validaciones, indican lo que dices.

**Comment by giansalex** [comment]
Corregido en https://github.com/giansalex/greenter-xml/commit/e4da15d5197c0175f28d7056d6b3abd4b7f910b5
