### ISSUE TITLE
documento afectado en Notas de crédito

### ISSUE THREAD

**Issue by AnthonyLJ96** [giansalex/greenter#37]
Buenas noches @giansalex 
![image](https://user-images.githubusercontent.com/32845362/47250907-2ddefb80-d3f0-11e8-9b96-a4071386fe78.png)

Quisiera saber que se le manda en el método "setNumDocfectado", "setSerie", "setCorrelativo", ¿ Todos hacen referencia al documento afectado por la nota de crédito?
Gracias.

**Comment by Gildus** [comment]
@AnthonyLJ96  Una nota de credito se hace en referencia a una factura, esto ya es terminos y definiciones basicas de contabilidad. 

setNumDocfectado: recibe como parametro la serie y numero de factura (segun imagen F001-111)
setSerie: es la seria de la nota de credito (segun imagen seria FF01).
setCorrelativo: es el correlativo de la nota de credito (segun imagen seria 123).

**Comment by giansalex** [comment]
Como dice @Gildus, es el comprobante afectado por la nota de crédito.
