### ISSUE TITLE
¿Por cuanto tiempo es válido el ticket que te devuelve sunat al emitir una comunicación de baja?

### ISSUE THREAD

**Issue by AnthonyLJ96** [giansalex/greenter#42]
Buenas noches @giansalex , el problema lo tengo en el ambiente de prueba de sunat o no sé si eso se dará porque es en este ambiente. Envío la comunicación de baja y me responde con status de aceptado pero después al consultar el ticket unos segundos después siempre me responde con ticket no existente.
¿Después de cuánto tiempo debería consultar el estado de la comunicación de baja?

Gracias de antemano.

**Comment by giansalex** [comment]
También me ha sucedido, no le tomes mucha importancia. Sucede en Beta, pero no debe ser recurrente, en greenter-sample si retorna el CDR

**Comment by AnthonyLJ96** [comment]
Gracias!
