### ISSUE TITLE
¿En que formato debe estar el certificado digital que utiliza greenter?

### ISSUE THREAD

**Issue by AnthonyLJ96** [giansalex/greenter#44]
Buenos días @giansalex , el certificado digital que adquirí está en formato .p12 y para sunat tengo entendido que tengo que convertirlo a formato .cer pero para greenter ¿ en qué formato debe estar?.
Gracias de antemano!.

**Comment by giansalex** [comment]
Greenter es en formato `.pem`

**Comment by giansalex** [comment]
en [requerimientos](https://giansalex.github.io/greenter/starter/#requerimientos), indica el formato del ceritificado, creo que puedes convertirlo a `.pfx`, y siguiendo [estos pasos](https://github.com/giansalex/xmldsig/blob/master/CONVERT.md#convert-to-pem) obtener el .pem (clave privada + publica)

**Comment by AnthonyLJ96** [comment]
@giansalex  gracias!
