### ISSUE TITLE
¿Cómo utilizo los parametros para emitir una factura con detracción?

### ISSUE THREAD

**Issue by AnthonyLJ96** [giansalex/greenter#46]
¿Cómo utilizo los parametros para emitir una factura con detracción?
setAmount()
setPercent()
setValueRef()

**Comment by giansalex** [comment]
Puedes revisar este ejemplo https://giansalex.github.io/greenter/examples/detraccion/

**Comment by AnthonyLJ96** [comment]
Buenas noches @giansalex , no encuentro en donde se señala el código de tipo de factura por detracción en los catálogos de Sunat. En el ejemplo que señalas '1001' pero no lo encuntro en el catálogo :c.

![image](https://user-images.githubusercontent.com/32845362/48178306-e0ff8e00-e2e6-11e8-9642-81141bb20a3d.png)

**Comment by giansalex** [comment]
Ese catálogo está desfasado, existe un Excel de validaciones en la sección de OSE cpe.sunat.gob.pe , allí puedes encontrarlo

**Comment by AnthonyLJ96** [comment]
a ya, @giansalex gracias!

**Comment by AnthonyLJ96** [comment]
Buenos días,
cuando emito una factura en dólares, debería hacer la conversión en solamente en soles para la detracción verdad?

**Comment by giansalex** [comment]
Hola @AnthonyLJ96 , cree otro issue #49, alli puedes verlo.
