### ISSUE TITLE
Error generando PDF, wkhtmltopdf 

### ISSUE THREAD

**Issue by byJuanjo** [giansalex/greenter#47]
Hola mi estimado, ya logre integrar todo y funciona perfectamente, pero me aparece el siguiente error al quiere generar la factura, podrias ayudarme por favor.

Error: Failed without error message: /home/systemat/public_html/systematic.com.pe/vendor/bin/wkhtmltopdf --no-outline --no-outline --viewport-size '1280x1024' --page-width '21cm' --page-height '29.7cm' --footer-html '/home/systemat/public_html/systematic.com.pe/greenter/resources/footer.html' '/tmp/tmp_wkhtmlto_pdf_9Dmmrs.html' '/tmp/tmp_wkhtmlto_pdf_eIXMsb.pdf'
![captura de pantalla 2018-11-07 a la s 13 35 06](https://user-images.githubusercontent.com/21320001/48152638-66a51e80-e292-11e8-834b-4ffe539c98cf.png)

Muchas gracias por tu apoyo.

**Comment by giansalex** [comment]
Es algo muy generico talvez 
- ese ejecutable no es para tu OS
- la opción [exec](http://php.net/manual/en/function.exec.php) esta deshabilitada
