### ISSUE TITLE
Error Comunicación de baja: IssueDate no debe ser mayor al Today

### ISSUE THREAD

**Issue by AnthonyLJ96** [giansalex/greenter#50]
Buenos días @giansalex , he obtenido el siguiente error en la comunicación de baja emitida ayer y enviada en una comunicación de baja a las 00:12 aproximadamente.

La fecha del IssueDate no debe ser mayor al Today - La fecha del IssueDate no debe ser mayor al Today
		         Detalle:xxx.xxx.xxx value='ticket: 201802937250131 error: Error : 2301 (nodo: "VoidedDocuments/cbc:IssueDate" valor: "2018-11-09")'

**Comment by giansalex** [comment]
Debe ser por la hora en que la enviaste, aun así es un problema de SUNAT, la zona horaria en la que este configurado sus servidores. Podrías reportarles.
Supongo que si lo envías ahora, si debe ser aceptada.

**Comment by AnthonyLJ96** [comment]
Probaré ahora y te comento como quedó

**Comment by giansalex** [comment]
Si, me quedo claro. Probablemente si hubieras colocado la fecha de ayer: `2018-11-08`, te hubiera aceptado.

**Comment by AnthonyLJ96** [comment]
efectivamente era eso. Gracias!
