### ISSUE TITLE
Consulta de comprobantes desde el sistema del contribuyente

### ISSUE THREAD

**Issue by AnthonyLJ96** [giansalex/greenter#51]
Buenos días @giansalex , que cosas se deben tener al implementar el portal para que el cliente consulte el comprobante emitido por una empresa, estoy viendo algunos portales y te pide los mismos datos como fecha de emisión, serie, correlativo y monto total de la venta, ¿esta es la estructura que debe seguir obligatoriamente o puede cambiar?. Veo que solo sirve para descargar una copia del comprobante.
Gracias.

**Comment by giansalex** [comment]
No hay ningún lineamiento, sunat solo exige que el cliente tenga disponible una pagina a la cual consultar, pero hay que verificar de alguna manera de que solo el receptor pueda verlo.
