### ISSUE TITLE
Correlativo en resumen 

### ISSUE THREAD

**Issue by AnthonyLJ96** [giansalex/greenter#52]
Buenos días @giansalex, habría problema si envío correlativo de los resúmenes repetidos?, verás es que en el sistema que estoy haciendo manejo varias sedes y cada sede maneja su propio resumen, cada una con su propio correlativo, creo que no debería manejarse así verdad?

**Comment by giansalex** [comment]
El principal objetivo es diferenciar los resumenes, si envías en una misma fecha varios resúmenes lo unico que las diferencia es el correlativo. Entonces el correlativo puede ser el mismo si la fecha del resumen es diferente.
