### ISSUE TITLE
Notas de crédito y débito en resumen de boletas

### ISSUE THREAD

**Issue by AnthonyLJ96** [giansalex/greenter#53]
Buenas tardes @giansalex , como indico el tipo de nota de crédito o débito en el resumen de boletas?, en tu ejemplo de greenter-sample pones como generar una nota de crédito haciendo referencia a una boleta pero ¿Cómo indico el tipo de nota de crédito que es?.

![image](https://user-images.githubusercontent.com/32845362/48644181-d19bd700-e9af-11e8-97bd-4e45c1f19590.png)

**Comment by giansalex** [comment]
es en `setTipoDoc` , puede ser 07  - Nota de Credito o **08 - Nota de Debito**

**Comment by giansalex** [comment]
Eso no es requerido en resumen diario.

**Comment by AnthonyLJ96** [comment]
Entonces no es necesario especificar eso para las nota de crédito para boletas?, le puedo dar el uso que yo crea conveniente?

**Comment by giansalex** [comment]
Las nota de credito como tal, `<CreditNote>` sea para boletas, deben cumplir los mismos requerimientos que para Facturas. El detalle es que el Resumen Diario no requiere esa información, pero al cliente se le debe entregar el xml de la nota de crédito con el código correcto en `TipodeNota`.

**Comment by AnthonyLJ96** [comment]
A ya ya, es decir, las notas de crédito para boletas solo se envían en el resumen diario sin indicar el tipo de el tipo de nota de crédito que son, el sistema ya debe de la empresa debe usarlo de la forma conveniente pero al cliente se le entrega la nota de crédito siguiendo el modelo de xml para nota de crédito específicamente, estoy bien?

**Comment by giansalex** [comment]
Así es.
