### ISSUE TITLE
Error conectando al servicio de SUNAT: "Could not connect to host"

### ISSUE THREAD

**Issue by necepurenko** [giansalex/greenter#54]
Hola, estoy intentando dar los primeros pasos para entender esta librería,  probé greenter-sample, tambien  greenter-firststeps y adicionalmente por separado los ejemplos. Lo primero que realice fue instalar greenter/greenter por medio de composer. El problema radica es que en todos los ejemplos me sale: string(25) "Could not connect to host" y los errores fueron 3803 y 3122, en en archivo de la sunat  ( ValidacionesCPEv20170814.xlsx – código de retorno) no aparece la serie 3xxx. Por favor, si me pueden aclarar las dudas: 1) en que parte de la librería manejan estos errores por que no lo consigo y 2) por que pasa esto si  greenter-sample en linea si funciona y a mi no. Si tengo internet, todo el equipo esta bien configurado. 

Error que sale en greenter-firststeps 
php factura.php 
object(Greenter\Model\Response\Error)#3803 (2) {
  ["code":protected]=>
  string(4) "HTTP"
  ["message":protected]=>
  string(25) "Could not connect to host"
}

**Comment by giansalex** [comment]
Esos códigos no son de SUNAT, el cogido es el que aparece en el campo `$error->getCode()`, pero en ese caso no pudo conectarse al servicio de SUNAT, verifica si puedes conectarte desde el navegador a los servicios listados [aqui](https://github.com/giansalex/greenter-ws).

**Comment by necepurenko** [comment]
Hola, gracias por contestar, en las conexiones disponibles en la versión beta probé con el navegador abrir con los 3 link, el resultado fue que me muestran el arbol, adicionalmente fui probando en la la librería See.php y FeFactory.php, En este ultimo verifique que en la funcion send genera   $xml = $this→getXmlSigned($document); pero no retorna (return $this->sender->send($document->getName(), $xml);)

**Comment by giansalex** [comment]
Usas algun proxy?, puedes ver [esta respuesta](https://stackoverflow.com/questions/4318870/soapfault-exception-could-not-connect-to-host)

**Comment by giansalex** [comment]
No creo que sea algun error de la libreria, prueba lo que indica el link que puse en el comentario anterior.,

**Comment by necepurenko** [comment]
Hola, gracias por contestar, en SoapClient.php → dentro del constructor le agregue el parametro:
parameters=[
    'stream_context' => stream_context_create([
        'ssl' => [
            'ciphers'=>'AES256-SHA',
        ],
    ]),
];

y el resultado fue: 

Respuesta SUNAT: La Factura numero F001-123, ha sido aceptada.

Uso linux, no se si tiene algo que ver.

**Comment by giansalex** [comment]
Realmente no ya que las pruebas unitarias de todas las librerias de Greenter se hacen bajo linux

**Comment by woalvarado** [comment]
Hola buen dia @giansalex  soy nuevo en esto, estaba haciendo la prueba en https://greenter-sample.herokuapp.com/
pues salio esto.
![image](https://user-images.githubusercontent.com/36551217/53923452-6c472100-4046-11e9-9e85-5169ec7300c5.png)

**Comment by giansalex** [comment]
Hola @woalvarado , el [servicio beta](https://e-beta.sunat.gob.pe/ol-ti-itcpfegem-beta/billService?wsdl) de sunat se ha caído.

**Comment by itamaradin15** [comment]
Tengo este inconveniente con mi sistema me sale el siguiente error en produccion  "production.INFO: Could not connect to host" lo raro es que a veces procesa la factura y a veces no.
Lo he probado en mi computadora local con las credenciales de produccion  y si funciona todas las veces.
 Pero al subirlo a mi vps digital ocean con ubuntu 18, me siguen saliendo el error en algunos documentos. Asumo que es alguna configuracion de mi dropple aun asi he desactivado el firewall UFW y no se soluciona aunque lei que no tiene nada que ver con firewall porque soap correr en el puerto 80 como esquema xml. si alguno le ha pasado seria de gran ayuda, he tenido que enviar las facturas todas las noches desde mi computadora local que si me funciona sin problemas
![Screenshot from 2019-05-26 16-36-21](https://user-images.githubusercontent.com/14314148/58387480-6a04bb00-7fd4-11e9-8d3a-9f586a83ac00.png)

**Comment by giansalex** [comment]
Hola @itamaradin15  , probaste está respuesta
https://github.com/giansalex/greenter/issues/54#issuecomment-440073541

**Comment by itamaradin15** [comment]
Si. Aun asi me sigue enviando algunas y otras no. 
![Screenshot from 2019-05-26 17-21-18](https://user-images.githubusercontent.com/14314148/58387822-28c3d980-7fdb-11e9-90b6-3c49aa3ebc8c.png)
