### ISSUE TITLE
Descuento en boletas a través del Resumen Diario

### ISSUE THREAD

**Issue by AnthonyLJ96** [giansalex/greenter#55]
Buenos días @giansalex , ¿Como haría para aplicar descuento en las boletas informadas por el resumen?, en el caso sea un descuento promocional y en el caso sea un descuento por nota de crédito. Se podría dar el caso de emitir en 0??, es decir aplicándole un descuento total?.
Gracias de antemano.

**Comment by giansalex** [comment]
Según la validación de SUNAT, el total puede ser igual a cero.

**Comment by AnthonyLJ96** [comment]
y en que campo incluiría ese descuento?, o simplemente puedo mandar todos los campos en 0 ?

**Comment by giansalex** [comment]
Sunat no considera esa información en el resumen diario, podrías probar en Beta.

**Comment by AnthonyLJ96** [comment]
Gracias!
