### ISSUE TITLE
Generar XML de boletas

### ISSUE THREAD

**Issue by AnthonyLJ96** [giansalex/greenter#56]
Buenas noches @giansalex , como es que se manejan los xml de las boletas?, es decir, tengo entendido que las boletas se informan mediante el resumen pero al enviar el correo al cliente en algunos casos es necesario enviarles el xml. De qué manera generamos este a través de greenter sin que lo enviemos a sunat?, o cómo es qué se maneja?, hay que volver a enviar el xml de la boleta sola a sunat a pesar de que ya haya sido informada a través del resumen para que tenga validez??. Gracias de antemano.

**Comment by giansalex** [comment]
Hola @AnthonyLJ96 , tu pregunta es muy válida, agregaré un ejemplo en la documentación.
Para generar el xml sin enviar a sunat existe el metodo `getXmlSigned`.
Ejm:
```php
$boleta = new Invoice();
// llenar datos de boleta
$xml = $see->getXmlSigned($boleta);
```

**Comment by AnthonyLJ96** [comment]
gracias @giansalex !

**Comment by jhonVargasT** [comment]
Hola que tal, disculpa que te interrumpa en tus labores pero he estado intentando hacer lo de la facturación me queda muchos vacíos. Se puede manejar tu código de forma gratuita o hay que pagar por la librería, soy nuevo en esto. Gracias por tomarte las molestias de contestar.

**Comment by giansalex** [comment]
Hola @jhonVargasT, puedes suberlo libremente. Si te es util, puedes retribuir contribuyendo reportando issues, codigo, donación.

**Comment by jhonVargasT** [comment]
Muchas gracias, vales un mundo, en serio que nos estas facilitando las cosas bastante. Muy agradecido por tu aporte

**Comment by marcuspc** [comment]
Buenas noches, estoy intentando hacer la CONSULTA CDR, pero me sale error, quisiera por favor me de una orientacion, adjunto el codigo utilizado, para una mejor comprension.

   use Greenter\Ws\Services\SunatEndpoints;
   use Greenter\Ws\Services\ConsultCdrService;
   use Greenter\Ws\Services\SoapClient;

    $ws = new SoapClient(SunatEndpoints::FE_CONSULTA_CDR.'?wsdl');
    $ws->setCredentials('20000000001MODDATOS','moddatos');

    $service = new ConsultCdrService();
    $service->setClient($ws);

    $arguments = [$ruc,$codigo_comprobante,$serie,intval($numero)];
    $result = $service->getStatus(...$arguments);

    if ($result->isSuccess()){
        $mensajeError =    '<p style="display: block; font-size:14px !important;">
                                <div class="alert alert-danger alert-bordered">
                                    <strong>CODIGO: </strong><em>'.$result->getCode().'</em><br>
                                    <strong>MENSAJE: </strong><em>'.$result->getMessage().'</em>
                                </div>
                            </p>';
    }

    if (!is_null($result->getCdrResponse())){
        $mensajeError =    '<p style="display: block; font-size:14px !important;">
                                <div class="alert alert-danger alert-bordered">
                                    <strong>Estado: </strong><em>'.$result->getCdrResponse()->getDescription().'</em><br>
                                    <strong>Obs: </strong><em>'.$result->getCdrResponse()->getNotes().'</em>
                                </div>
                            </p>';
    }else{
        $mensajeError =    '<p style="display: block; font-size:14px !important;">
                                <div class="alert alert-danger alert-bordered">
                                    <strong>Error: </strong><em>'.$result->getError()->getMessage().'</em><br>                               
                                </div>
                            </p>';
    }

**Comment by giansalex** [comment]
Hola @marcuspc , cual es el error?
> Tambien, en el primer tal vez falta un `return` cuando no es exitoso.
```php
// ...
$result = $service->getStatus(...$arguments);

if ($result->isSuccess()){
    $mensajeError =    '....';
     return;
}
```

**Comment by marcuspc** [comment]
Buenas noches @giansalex , gracias por la ayuda, pude revisar que en las facturas todo va bien, pero obtengo estas observaciones:

4093 - El codigo de ubigeo del domicilio fiscal del emisor no es válido - : 4093: Valor no se encuentra en el catalogo: 13 (nodo: "cac:RegistrationAddress/cbc:ID" valor: "")
4317 - Debe consignar el Total Precio de Venta - INFO: 4317 (nodo: "/" valor: "")

En el caso de las BOLETAS: 
No me devuelve ninguna mensaje.

Agradezco tu respuesta, Saludos.

**Comment by giansalex** [comment]
@marcuspc puedes tomar como guía este ejemplo https://github.com/thegreenter/demo/blob/master/examples/boleta.php ,
y en especifico en las observaciones que tienes, debes colocar el ubigeo en la direccion de la empresa y el campo `$invoice->setSubTotal();`

**Comment by marcuspc** [comment]
@giansalex , gracias por la pronta respuesta, mi consulta ahora es si hay forma de consultar el estado de mi BOLETA, así como lo hay en consulta de FACTURA, gracias.

**Comment by giansalex** [comment]
Hola @marcuspc , si puedes consultar el estado usando el API de Consulta integrada de SUNAT, aqui hay una implementacion en PHP https://github.com/thegreenter/consulta-cpe

**Comment by marcuspc** [comment]
Hola @giansalex , muchas gracias por la información brindada, con respecto a consultas por DNI y RUC, greenter tiene esa funcionalidad, es decir si digito el DNI o RUC, me pueda facilitar el nombre, razón social, dirección, ubigeo, habido, activo?
Y con respecto a las compras electrónicas, existe la posibilidad de recuperar esa información consultando con greenter?

**Comment by giansalex** [comment]
@marcuspc puedes usar [peru-consult](https://github.com/giansalex/peru-consult), hace uso de paginas publicas de SUNAT.
Sobre consulta de compras electrónicas, no hay algo publicado por SUNAT.

**Comment by marcuspc** [comment]
@giansalex muchas gracias, otra consulta adicional.
Por ejemplo si quiero registrar la venta de **medio** TUBO, podria poner en cantidad 0.5 (NIU) o como podria hacerlo???,
gracias.

**Comment by giansalex** [comment]
@marcuspc si, puede contener hasta 10 decimales.

**Comment by marcuspc** [comment]
@giansalex, muchas gracias por tus respuestas, 
Abusando un poco de tu ayuda frecuente, quisiera pedirte una orientación o recomendación acerca de algún proveedor de dominio y hosting para alojar los proyectos que vengo desarrollando, pude revisar bluehost, pero no estoy muy seguro que pueda subir mi proyecto que no usa wordpress, uso php sin ningun framework.
Agradezco de antemano por la respuesta que me puedas brindar.
Saludos cordiales.

**Comment by gerson248** [comment]
Hola @giansalex, tenia una consulta en como podría obtener la información de una factura, estaba haciéndolo así, pero no muestra la serie del documento que quiero .

`$file = DIR_DOCUMENTOS_FILES_TMP.DS.'ina_548_20601855551-01-_FPP1-163.xml';
			$xml = file_get_contents($file);
			$invoiceParser = new InvoiceParser();
			$rsDocumento = $invoiceParser->parse($xml);
                        echo $rsDocumento->getSerie()`
