### ISSUE TITLE
Error en producción

### ISSUE THREAD

**Issue by debugsito** [giansalex/greenter#58]
Buenas tardes @giansalex , tengo una consulta, verás, tuve un problema al generar una factura el día de ayer, me devolvió el siguiente error. 
El XML no contiene el tag cac:Item/cbc:Description en el detalle de los Items - El XML no contiene el tag cac:Item/cbc:Description en el detalle de los Items
            Detalle:
            xxx.xxx.xxx value='ticket: 201803055016099 error: Error en la linea: 1: 2026 (nodo: "cac:Item/cbc:Description" valor: "")'

Estoy revisando a qué se debió ese problema en mi sistema pero ese es otro tema. El tema es que el usuario al ver el error intentó anularla y en la comunicación de baja que se envió me devolvió el siguiente error: "Factura a dar de baja no se encuentra registrada en SUNAT - ". 

Mis pregunta son las siguientes:
¿Esa númeración de factura ya no sirve?
¿Debería hacer algo con esos errores, informarlos o algo?

Gracias de antemano.

**Comment by giansalex** [comment]
Si puedes utilizarla, ya que el comprobante no existe para SUNAT.

**Comment by debugsito** [comment]
Y pasa algo si la dejo sin utilizarla?

**Comment by giansalex** [comment]
Consulta con tu contadora.
