### ISSUE TITLE
Consulta para enviar xml generado previamente

### ISSUE THREAD

**Issue by AnthonyLJ96** [giansalex/greenter#59]
Buenas tardes @giansalex , hay alguna forma de enviar solo el xml ya generado por la librería?. Verás hoy emití una factura y sunat me devolvió un error del tipo HTTP con descripción 'Bad Gateway' el cual no tenía contenplado y pues el usuario ignoró la alerta que se le mostró y generó otra factura que si fue válida, llamé a Sunat y me dijeron que vuelva a emitir la factura tal cuál y después le dé de baja.

Gracias de antemano.

**Comment by giansalex** [comment]
Parece lo mismo que esto https://github.com/giansalex/greenter-sample/issues/46
