### ISSUE TITLE
Serie para NOTAS DE CREDITO BOLETAS Y FACTURAS

### ISSUE THREAD

**Issue by byJuanjo** [giansalex/greenter#63]
Buenas tardes, una consulta para generar una nota de credito de **FACTURAS**, se envía directamente a la sunat despues de anular la factura cierto?
Su serie puede ser **FF01**.

En el caso de las notas de creditos de **BOLETAS** si se deben enviar por resumen diario y su serie puede ser **B001**?

**Comment by giansalex** [comment]
Hola Juanjo, la nota de crédito se envía después de enviar la factura y este aceptada. Si animaste la factura por comunicación de baja, no requeriría NCR. 
Acerca de las series, es la base inicial de facturación electrónica, facturas y NCR relacionadas empiezan con F, el resto es alfanumérico. Para las boletas lo mismo, con B.
