### ISSUE TITLE
isSuccess() devuelve false cuando el comprobante tiene errores

### ISSUE THREAD

**Issue by AnthonyLJ96** [giansalex/greenter#64]
Buenos días @giansalex , tengo una duda, yo tenía entendido que el método isSuccess() devolvía true si es que había una conexión con sunat y false cuando esta la rechazaba, por ejemplo cuando Sunat se cae, estoy en lo cierto o hubieron cambios con esto?

**Comment by giansalex** [comment]
Hola @AnthonyLJ96, sigue siendo igual, pero cuando la rechaza es porque no pasa la validación de sunat considerado como excepciones, allí devuelve los errores.

**Comment by AnthonyLJ96** [comment]
Entonces se considera como error cuando sunat rechaza la conexión o cuando hay errores de  validación de tipo excepción?

**Comment by giansalex** [comment]
en ambos casos, `isSuccess` es false, al lanzarlo como excepción, es considerado como un rechazo a la conexión.

**Comment by AnthonyLJ96** [comment]
Gracias
