### ISSUE TITLE
Error con método isSuccess de factura en ambiente de Desarrollo de Sunat

### ISSUE THREAD

**Issue by AnthonyLJ96** [giansalex/greenter#65]
Buenas tardes @giansalex , verás estoy probando en el ambiente de desarrollo de sunat y cuando envío un factura con un ruc erróneo este método me retorna false, cuando debería ser true ya que no es un error del tipo excepción. Gracias.

**Comment by giansalex** [comment]
Debe ser que sunat lo esta enviando como excepción, no todas las cosas de Producción funcionan igual en Beta.

**Comment by AnthonyLJ96** [comment]
Entonces no tendré problemas con esto en producción?

**Comment by giansalex** [comment]
No
