### ISSUE TITLE
Crear xml de boletas sin enviarlo a Sunat

### ISSUE THREAD

**Issue by AnthonyLJ96** [giansalex/greenter#67]
Buenas tardes @giansalex , tengo entendido que las boletas no son necesarias enviarlas una a una ya que se envían en el resumen diario, sin embargo, es obligatorio enviarlas al cliente por correo eléctronico en formato xml junto a su representación en pdf, de qué manera puedo hacer esto?

**Comment by giansalex** [comment]
Esto es un poco extraño, ya que lo preguntaste en #56

**Comment by AnthonyLJ96** [comment]
Si, sorry
