### ISSUE TITLE
SoapClient::__doRequest(): SSL: Connection reset by peer, Code: 0, File: {ROOT}/greenter/ws/src/Ws/Services/SoapClient.php, Line: 61

### ISSUE THREAD

**Issue by AnthonyLJ96** [giansalex/greenter#68]
Buenas tardes @giansalex , ya que estos días sunat ha estado caído, al momento de intentar emitir comprobantes he estado observando este error en mi log, es decir, no lo he podido recibir con el método getErrors(), cómo podría tratar esto?

**Comment by giansalex** [comment]
Hola @AnthonyLJ96, esto parece un problema interno en **PHP SoapClient**, [aqui la referencia](https://www.php.net/manual/es/soapclient.dorequest.php#105380)
