### ISSUE TITLE
seria muy buena idea obtener el <ds:DigestValue> del documento firmado en $see 

### ISSUE THREAD

**Issue by werpoz** [giansalex/greenter#69]
<b>buenas tardes<\b>
buenas alguna idea de extraer <ds:DigestValue>  de $see->getXmlSigned($invoice);

**Comment by giansalex** [comment]
Hola @werpoz,  puedes ver este ejemplo
https://github.com/giansalex/greenter-sample/blob/master/src/Util.php#L202

**Comment by werpoz** [comment]
gracias , en el core no se incluye esa clase , muchas gracias por tu tiempo @giansalex

**Comment by giansalex** [comment]
Esta incluido en [@greenter/report](https://github.com/giansalex/greenter-report)
