### ISSUE TITLE
Formato de números de los montos de Precio

### ISSUE THREAD

**Issue by erajuan** [giansalex/greenter#73]
Agregar formato a los montos según la documentación de sunat ( n(12,2) )
number_format

20.00000 -> 20.00
```php
{{ monto|number_format(2, '.') }}
```

**Comment by giansalex** [comment]
Hola @erajuan , se aplica el formato de 2 decimales a casi todos los montos excepto al precio unitario, alli puede tener mas decimales, lo ideal es poder determinar la cantidad de decimales y de acuerdo a ello mostrar el formato aceptando como mínimo 2 decimales y no los 6 que cuenta actualmente.
Pero aun no esta implementado.

**Comment by giansalex** [comment]
El cambio fue realizado en https://github.com/giansalex/greenter-xml/commit/7549af81d6af121aac19e21f3ef80067b2b061f5
