### ISSUE TITLE
XML no genera lineas de anticipo

### ISSUE THREAD

**Issue by leog1992** [giansalex/greenter#74]
Buen dia, estimado, cuando genero una factura con anticipo en el XML no agrega las lineas de anticipo, documento de referencia ni descuenta.
y en la linea de item detail vuelve a quitar el igv producto.
Gracias,.

**Comment by giansalex** [comment]
Hola @leog1992 , probablemente no estas la entidad correcta al campo, deberia ser un `Prepayment[]`
[Ejemplo](https://giansalex.github.io/greenter/examples/anticipo/)

**Comment by leog1992** [comment]
Lo hago igual que tú ejemplo, pero nada en el xml.

**Comment by giansalex** [comment]
He creado un ejemplo en [greenter-sample](https://greenter-sample.herokuapp.com/), con el ejemplo que te envie, y aparecen los campos.
![image](https://user-images.githubusercontent.com/14926587/58041574-0a06a400-7afe-11e9-8d61-4cc8a9f2c70c.png)

Puedes intentar actualizar los paquetes y borrar la carpeta `/cache`

**Comment by leog1992** [comment]
$prepago = new Prepayment();
$prepago->setTipoDocRel('02')// catalog. 12
        ->setNroDocRel($c_anticipo->getDocumento())
        ->setTotal(number_format($c_anticipo->getTotal() / 1.18, 2, ".", ""));

invoice ...
....
->setMtoImpVenta($total)
    ->setAnticipos($prepago)
    ->setTotalAnticipos(number_format($c_anticipo->getTotal() / 1.18, 2, ".", ""));

**Comment by giansalex** [comment]
`->setAnticipos()` recbie un array , deberia ser `setAnticipos([$prepago])`

**Comment by leog1992** [comment]
no me habia dado cuenta de esto.
object(Greenter\Model\Response\Error)#123 (2) { ["code":protected]=> string(4) "2521" ["message":protected]=> string(257) "El dato ingresado debe indicar SERIE-CORRELATIVO del documento que se realizo el anticipo. - Detalle: xxx.xxx.xxx value='ticket: 1558375597259 error: Documento Relacionado : 02-f001-42: 2521 (nodo: "cac:AdditionalDocumentReference/cbc:ID" valor: "f001-42")'" } {"success":false,"resultado":"error al procesar"}

**Comment by leog1992** [comment]
{"success":true,"resultado":{"nombre_archivo":"20445256740-01-F001-58","direccion_xml":"http:\/\/lunasystemsperu.com\/clientes\/caldas\/\/greenter\/files\/20445256740-01-F001-58.xml","direccion_qr":"http:\/\/lunasystemsperu.com\/clientes\/caldas\/\/greenter\/generate_qr\/temp\/20445256740-01-F001-58.png","hash":"VB0J3nzCtrZafS+18+CKIAzkWHw=","descripcion_cdr":"La Factura numero F001-58, ha sido aceptada"}}

**Comment by leog1992** [comment]
el problema era q "f001" estaba con minusculas, y tenia q ser "F001"

**Comment by leog1992** [comment]
Gracias. :D

**Comment by leog1992** [comment]
estimado en beta si genera el xml con sus lineas de anticipo pero en produccion no
beta: 
http:\/\/lunasystemsperu.com\/clientes\/caldas\/\/greenter\/files\/20445256740-01-F001-59.xml
en produccion
http:\/\/lunasystemsperu.com\/clientes\/caldas\/\/greenter\/files\/20445256740-01-F001-60.xml

**Comment by leog1992** [comment]
estimado en produccion no general correctamente el xml, ni sale error.


Luis E. Oyanguren Giron
Analista - Programador
LUNA SYSTEMS PERU

C: 936507153

E: leog.1992@gmail.com
E: loyangureng@lunasystemsperu.com
F: facebook.com/lunasystemsperu
W: www.lunasystemsperu.com

**Comment by leog1992** [comment]
estimado en produccion no genera el xml completo, pero en beta si
