### ISSUE TITLE
XML sin lineas de anticipo, solo en produccion

### ISSUE THREAD

**Issue by leog1992** [giansalex/greenter#75]
Estimado, buenas tardes, en modo beta Greenter si genera el XML con sus lineas de anticipo, pero al cambiarlo a Produccion, no genera las lineas adicionales de anticipo

**Comment by giansalex** [comment]
El cambio de url del servicio no afecta la generación del XML, si esta en algún hosting puede ser problemas de permiso en la carpeta `/cache`

**Comment by leog1992** [comment]
la carpeta si tiene permisos, pero el xml no genera con anticipo.
![Captura de pantalla_2019-05-20_16-05-23](https://user-images.githubusercontent.com/8444234/58052458-7bece680-7b1a-11e9-9770-23a8f01bfd8c.png)

**Comment by giansalex** [comment]
actualiza el repositorio de `greenter-sample` con el ultimo ejemplo. Alli deberia aparecer, lo mas probable es que se un tema de codigo de tu lado. Si vas al [ejemplo desplegado](https://greenter-sample.herokuapp.com/) , veras que si lo muestra.

**Comment by leog1992** [comment]
como puedo hacer funcionar esto en el xml (invoice2.1.xml.twig)
<cbc:Note>existe anticipo:  </cbc:Note>
<cbc:Note>{{ doc.anticipos }} </cbc:Note>

**Comment by leog1992** [comment]
// Envio a SUNAT.
$see = $util->getSee(SunatEndpoints::FE_BETA);
//$see = $util->getSee(SunatEndpoints::FE_PRODUCCION);
en beta: 
object(Greenter\Model\Response\Error)#124 (2) { ["code":protected]=> string(4) "HTTP" ["message":protected]=> string(9) "Forbidden" } 
{"success":false,"resultado":"error al procesar"}

`<cbc:DocumentCurrencyCode>PEN</cbc:DocumentCurrencyCode>
    <cbc:Note>existe anticipo:  </cbc:Note>
    <cbc:Note><br/>
<b>Notice</b>:  Array to string conversion in <b>/home/lunasystems/public_html/clientes/caldas/greenter/cache/3e/3e65f91693c6a17f48a6f69fb2c89aae72618f8b8a00df49f65579bbe269dc4f.php</b> on line <b>88</b><br/>
Array </cbc:Note>
<cac:AdditionalDocumentReference>
        <cbc:ID>F001-65</cbc:ID>
        <cbc:DocumentTypeCode>02</cbc:DocumentTypeCode>
        <cbc:DocumentStatusCode>1</cbc:DocumentStatusCode>
        <cac:IssuerParty>
            <cac:PartyIdentification>
                <cbc:ID schemeID="6">20445256740</cbc:ID>
            </cac:PartyIdentification>
        </cac:IssuerParty>
    </cac:AdditionalDocumentReference>`

**Comment by giansalex** [comment]
`Note: existe anticipo`, no debería estar alli, a menos que hayas modificado el template.
El caso del error, es un problema en el servidor de sunat` (HTTP Forbidden)`

**Comment by leog1992** [comment]
si, eso quiere decir q si envia la variable anticipo, pero cuando cambio a produccion nunca llega esa variable.

**Comment by leog1992** [comment]
no encuentro el problema, pero me di cuenta q si vuelvo a generar el xml si aparece. parece q al enviar a produccion es mas rapido.

`<?php

error_reporting(E_ALL);
ini_set('display_errors', '1');

date_default_timezone_set('America/Lima');

use Greenter\Model\Client\Client;
use Greenter\Model\Company\Address;
use Greenter\Model\Company\Company;
use Greenter\Model\Sale\Invoice;
use Greenter\Model\Sale\Legend;
use Greenter\Model\Sale\Prepayment;
use Greenter\Model\Sale\SaleDetail;
use Greenter\Ws\Services\SunatEndpoints;

require __DIR__ . '/../vendor/autoload.php';

require __DIR__ . '/../../class/cl_venta.php';
require __DIR__ . '/../../class/cl_cliente.php';
require __DIR__ . '/../../class/cl_entidad.php';
require __DIR__ . '/../../class/cl_ventas_detalle.php';
require __DIR__ . '/../../class/cl_venta_anticipo.php';

require __DIR__ . '/../../class/cl_numero_letras.php';
require __DIR__ . '/../../greenter/generate_qr/class/cl_generar_qr.php';

$util = Util::getInstance();

$c_venta = new cl_venta();

$c_venta->setId_venta(filter_input(INPUT_GET, 'id_venta'));
$c_venta->setPeriodo(filter_input(INPUT_GET, 'periodo'));
$c_venta->datos_venta();

$id_moneda = $c_venta->getMoneda();
$valor_moneda = "PEN";
if ($id_moneda == 2) {
    $valor_moneda = "USD";
}

$c_anticipo = new cl_venta_anticipo();
$c_anticipo->setIdVenta($c_venta->getId_venta());
$c_anticipo->setPeriodoVenta($c_venta->getPeriodo());
$c_anticipo->obtener_datos();

$c_cliente = new cl_cliente();
$c_cliente->setCodigo($c_venta->getId_cliente());
$c_cliente->validar_cliente();

$c_entidad = new cl_entidad();
$c_entidad->setRuc($c_cliente->getRuc());
$c_entidad->obtener_datos();

$client = new Client();
$client->setTipoDoc('6')
    ->setNumDoc($c_entidad->getRuc())
    ->setRznSocial(utf8_encode($c_entidad->getRazon_social()))
    ->setAddress((new Address())
        ->setDireccion(utf8_encode($c_entidad->getDireccion())));

$c_empresa = new cl_entidad();
$c_empresa->setRuc(20445256740);
$c_empresa->obtener_datos();

$empresa = new Company();
$empresa->setRuc(20445256740)
        ->setNombreComercial(utf8_encode("INDUSTRIA PESADA CALDAS E.I.R.L."))
        ->setRazonSocial(utf8_encode("INDUSTRIA PESADA CALDAS E.I.R.L."))
        ->setAddress(
            (new Address())
            ->setUbigueo("021809")
            ->setDistrito(utf8_encode("NUEVO CHIMBOTE"))
            ->setProvincia("SANTA")
            ->setDepartamento("ANCASH")
            ->setUrbanizacion('-')
            ->setCodLocal('0000')
            ->setDireccion(utf8_encode("AV. JOSE PARDO NRO. S/N Z.I. SANTA ANGELA - ANCASH SANTA NUEVO CHIMBOTE"))
        );

//echo $total_anticipo = $c_anticipo->getTotal() . "<br>";

$total_venta = $c_venta->getTotal();
$total_anticipo = $c_anticipo->getTotal();
$total_nuevo = $total_venta - $total_anticipo;
$subtotal_nuevo = $total_nuevo / 1.18;
$igv_nuevo = $subtotal_nuevo * 0.18;

$invoice = new Invoice();

$subtotal_anterior = number_format($total_venta / 1.18, 2, ".", "");
$subtotal = number_format($subtotal_nuevo, 2, ".", "");
$igv = number_format($igv_nuevo, 2, ".", "");
$total = number_format($total_nuevo, 2, ".", "");

$invoice
    ->setAnticipos([
        (new Prepayment())
            ->setTipoDocRel('02')// catalog. 12
            ->setNroDocRel(strtoupper($c_anticipo->getDocumento()))
            ->setTotal(number_format($c_anticipo->getTotal() / 1.18, 2, ".", ""))
    ])
    ->setTotalAnticipos(number_format($c_anticipo->getTotal() / 1.18, 2, ".", ""));
    
$invoice
    ->setUblVersion('2.1')
    ->setFecVencimiento(new \DateTime())
    ->setTipoOperacion('0101')
    ->setTipoDoc('01')
    ->setSerie($c_venta->getSerie())
    ->setCorrelativo($c_venta->getNumero())
    ->setFechaEmision(new \DateTime())
    ->setTipoMoneda(utf8_encode($valor_moneda))
    ->setClient($client)
    ->setCompany($empresa)
    ->setMtoOperGravadas($subtotal)
    ->setMtoIGV($igv)
    ->setTotalImpuestos($igv)
    ->setValorVenta($subtotal)
    ->setMtoImpVenta($total);

/*
 * ->setAnticipos([
        (new Prepayment())
            ->setTipoDocRel('02')// catalog. 12
            ->setNroDocRel(strtoupper($c_anticipo->getDocumento()))
            ->setTotal(number_format($c_anticipo->getTotal() / 1.18, 2, ".", ""))
    ])
 */
$c_productos = new cl_ventas_detalle();
$c_productos->setId_venta($c_venta->getId_venta());
$c_productos->setPeriodo($c_venta->getPeriodo());

$items = $c_productos->ver_productos();

$array_items = array();

foreach ($items as $value) {
    $item = new SaleDetail();
    $item->setCodProducto($value['id_item'])
        ->setUnidad('NIU')
        ->setDescripcion(utf8_encode($value['descripcion']))
        ->setCantidad($value['cantidad'])
        ->setMtoValorUnitario(number_format($value['precio'], 2, '.', ''))
        ->setMtoValorVenta(number_format($value['precio'] * $value['cantidad'], 2, '.', ''))
        ->setMtoBaseIgv(number_format($value['precio'] * $value['cantidad'], 2, '.', ''))
        ->setPorcentajeIgv(18)
        ->setIgv(number_format($value['precio'] * $value['cantidad'] * 0.18, 2, '.', ''))
        ->setTipAfeIgv('10')
        ->setTotalImpuestos(number_format($value['precio'] * $value['cantidad'] * 0.18, 2, '.', ''))
        ->setMtoPrecioUnitario(number_format($value['precio'] * 1.18, 2, '.', ''));
    $array_items[] = $item;
}

$invoice->setDetails($array_items);

$c_numeros = new cl_numero_letras();
$numeros = utf8_encode($c_numeros->to_word(number_format($total_nuevo, 2, ".", ""), $valor_moneda));
$invoice->setLegends([
    (new Legend())
        ->setCode('1000')
        ->setValue($numeros)
]);

// Envio a SUNAT.
//$see = $util->getSee(SunatEndpoints::FE_BETA);
$see = $util->getSee(SunatEndpoints::FE_PRODUCCION);

/** Si solo desea enviar un XML ya generado utilice esta función* */
//$res = $see->sendXml(get_class($invoice), $invoice->getName(), file_get_contents($ruta_XML));

$res = $see->send($invoice);
$util->writeXml($invoice, $see->getFactory()->getLastXml());

$respuesta = array();
if ($res->isSuccess()) {
    $nombre_archivo = $invoice->getName();
    $dominio = "http://" . $_SERVER["HTTP_HOST"] . "/clientes/caldas/";
    $nombre_xml = $dominio . "/greenter/files/" . $invoice->getName() . ".xml";
    $hash = $util->getHash($invoice);

    //generar qr
    $qr = $c_empresa->getRuc() . "|" . "01" . "|" . $c_venta->getSerie() . "-" . $c_venta->getNumero() . "|" . $igv . "|" . $total . "|" . $c_venta->getFecha_factura() . "|" . "06" . "|" . $c_cliente->getRuc();
    $c_generar = new cl_generar_qr();
    $c_generar->setTexto_qr($qr);
    $c_generar->setNombre_archivo($nombre_archivo);
    $c_generar->generar_qr();

    //obtener url de qr
    $url_qr = $dominio . "/greenter/generate_qr/temp/" . $nombre_archivo . ".png";

    //obtener cdr y guardar en json
    /*     * @var $res \Greenter\Model\Response\BillResult */
    $cdr = $res->getCdrResponse();
    $util->writeCdr($invoice, $res->getCdrZip());
    $descripcion = $cdr->getDescription();

    $respuesta = array(
        "success" => true,
        "resultado" => array(
            "nombre_archivo" => $nombre_archivo,
            "direccion_xml" => $nombre_xml,
            "direccion_qr" => $url_qr,
            "hash" => $hash,
            "descripcion_cdr" => $descripcion
        )
    );

    $util->getResponseFromCdr($cdr);
} else {
    var_dump($res->getError());
    echo "<br>";
    $respuesta = array(
        "success" => false,
        "resultado" => "error al procesar"
    );
}

echo json_encode($respuesta);

`

**Comment by giansalex** [comment]
@leog1992 entonces se soluciono?

**Comment by Gildus** [comment]
para mi son temas de permisos, al parecer ya lo soluciono; es el problema de estar en un hosting compartido te limita mucho y no puedes perfilar con herramientas.

**Comment by leog1992** [comment]
Si ya está solucionado, el problema no era el hosting ni la librería, era
una variable . También me di cuenta q en el cdr hay observaciones los
montos no coinciden, tienes q corregir tu ejemplo

Luis E. Oyanguren Giron
Analista - Programador
LUNA SYSTEMS PERU

C: 936507153

E: leog.1992@gmail.com
E: loyangureng@lunasystemsperu.com
F: facebook.com/lunasystemsperu
W: www.lunasystemsperu.com

**Comment by giansalex** [comment]
Si, en realidad los montos son modificados para probar ciertas funcionalidades, el calculo correcto se ha perdido, tendré en cuenta lo que mencionas.

**Comment by leog1992** [comment]
4299 - La sumatoria del total valor de venta - operaciones gravadas de l&#237;nea no corresponden al total - INFO : 4299 (nodo: "cac:TaxSubtotal/cbc:TaxableAmount" valor: "2400.00")</cbc:Note><cbc:Note>4290 - El c&#225;lculo del IGV es Incorrecto - INFO : 4290 (nodo: "cac:TaxSubtotal/cbc:TaxAmount" valor: "432.00")
