### ISSUE TITLE
Observaciones CDR, Sumatoria total no corresponde

### ISSUE THREAD

**Issue by leog1992** [giansalex/greenter#76]
4299 - La sumatoria del total valor de venta - operaciones gravadas de l&#237;nea no corresponden al total - INFO : 4299 (nodo: "cac:TaxSubtotal/cbc:TaxableAmount" valor: "2400.00")
4290 - El c&#225;lculo del IGV es Incorrecto - INFO : 4290 (nodo: "cac:TaxSubtotal/cbc:TaxAmount" valor: "432.00")

observacion en nota de credito. factura con anticipo.
he probado de acuerdo al ejemplo, he aumentado el igv, sin IGV, de varias maneras siempre sale alguna observacion, como puedo corregir esto?

**Comment by leog1992** [comment]
2400 es el sub total
432 es el igv
2832 es el total

**Comment by giansalex** [comment]
Hola @leog1992 , eso ya es un tema de contabilidad, eso te aparece en el servicio Beta?

**Comment by leog1992** [comment]
En producción, no creo q sea contabilidad.
Pongo los datos según ejemplo.


Luis E. Oyanguren Giron
Analista - Programador
LUNA SYSTEMS PERU

C: 936507153

E: leog.1992@gmail.com
E: loyangureng@lunasystemsperu.com
F: facebook.com/lunasystemsperu
W: www.lunasystemsperu.com

**Comment by giansalex** [comment]
A cual ejemplo te refieres? la librería no hace ningún calculo, solo envía los montos seteados, que deberia provenir del calculo realizado por algún sistema de ventas.

**Comment by giansalex** [comment]
@leog1992 , realice la validación y si falto incluir en el ejemplo la seccion de descuentos por anticipo.
El ejemplo ha sido actualizado.
