### ISSUE TITLE
Eliminar Tabulaciones y saltos de linea

### ISSUE THREAD

**Issue by erajuan** [giansalex/greenter#78]
Representaria menos 2KB aprox por XML
{% spaceless %}
<xml
{% endspaceless %}

**Comment by giansalex** [comment]
Hola @erajuan, gracias por la sugerencia, seria genial que en un fork de [greenter/xml](https://github.com/giansalex/greenter-xml), introdujeras ese cambio.

**Comment by giansalex** [comment]
Hecho en https://github.com/giansalex/greenter-xml/pull/23
