### ISSUE TITLE
problems

### ISSUE THREAD

**Issue by abelnexus** [giansalex/greenter#8]
C:\xampp\htdocs\greenter>composer require greenter/greenter
Using version ^2.0 for greenter/greenter
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package greenter/greenter No version set (parsed as 1.0.0) is satisfiable by greenter/greenter[No version set (parsed as 1.0.0)] but these conflict with your requirements or minimum-stability.

Installation failed, reverting ./composer.json to its original content.

**Comment by giansalex** [comment]
Prueba colocando la dependencia directamente en el `composer.json`
```json
{
  "require": {
    "greenter/greenter": "^2.0"
  }
}
```
luego ejecutas
```bash
composer update
```

**Comment by abelnexus** [comment]
nada, no logro hacerlo funcionar :´(

**Comment by abelnexus** [comment]
![captura](https://user-images.githubusercontent.com/34687414/34454968-bcb6c782-ed43-11e7-96df-a2200846af64.PNG)

**Comment by abelnexus** [comment]
al inciar en localhost no me aparece nada, me falta archivos ? ayuda+

**Comment by giansalex** [comment]
Greenter es una libreria, si quieres probar su funcionamiento aqui hay un ejemplo [greenter-sample](https://github.com/giansalex/greenter-sample)

**Comment by abelnexus** [comment]
muchas gracias por tu tiempo, quizás tengas un ejemplo de como crear. desde un formulario la factura en xml y firmarlo ?

**Comment by giansalex** [comment]
Aun no lo tengo disponible, pero estoy realizando un [facturador web](https://github.com/giansalex/invoice-fe) empleando Symfony4, pero lo he dejado por ahora, para desarrollar actualizar los xml al standard UBL 2.1

**Comment by giansalex** [comment]
descontinuado
