### ISSUE TITLE
Atributo Type en Password es requerido (Soap)

### ISSUE THREAD

**Issue by giansalex** [giansalex/greenter#80]
Haciendo pruebas con el OSE (`https://osetesting.bizlinks.com.pe/ol-ti-itcpe/billService?WSDL`), retorna el siguiente error:
```
A security error was encountered when verifying the message Caused by: BSP:R4201: Any PASSWORD MUST specify a Type attribute
```
El resultado esperado de las cabecera de seguridad enviado para el nodo de password deberá ser:
```xml
<ns2:Password Type="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-username-token-profile-1.0#PasswordText">moddatos</ns2:Password>
```
Archivo a modificar:
[src/Ws/Header/WSSESecurityHeader.php](https://github.com/giansalex/greenter-ws/blob/master/src/Ws/Header/WSSESecurityHeader.php)

**Comment by giansalex** [comment]
Posible guia [add_attribute_to_SoapVar](https://fvue.nl/wiki/Php:_Soap:_How_to_add_attribute_to_SoapVar), o setear ~directamente el XML~ (poco seguro)
```php
new SoapVar('<ns2:Password Type="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-username-token-profile-1.0#PasswordText">moddatos</ns2:Password>', XSD_ANYXML)
```

**Comment by KhanMaytok** [comment]
Excelente

**Comment by ericsonvb** [comment]
Por si quedan algunas dudas las lineas quedarían de la siguiente forma:
 [
                    new SoapVar($username, XSD_STRING, null, null, 'Username', self::WSS_NAMESPACE),
                    new SoapVar('<ns2:Password Type="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-username-token-profile-1.0#PasswordText">'.$password.'</ns2:Password>', XSD_ANYXML)

                ],

**Comment by giansalex** [comment]
El cambio fue realizado en https://github.com/giansalex/greenter-ws/pull/14
