### ISSUE TITLE
.CER to .PEM

### ISSUE THREAD

**Issue by KhanMaytok** [giansalex/greenter#81]
Hola, quizá esta pregunta está fuera de lugar, pero un OSE me entregó en certificado en .cer y al convertirlo a .pem obtuve el error

    Warning: openssl_sign(): supplied key param cannot be coerced into a private key  

Estoy haciendo algo mal? El comando que usé:

    openssl x509 -inform der -in cert.cer -out cert.pem

**Comment by giansalex** [comment]
Creo que estás usando el certificado equivocado, tendrías que preguntar al OSE que hacer con ese certificado.

**Comment by giansalex** [comment]
Probablemente ese certificado necesites instalarlo en tu máquina, para conexión con sus servicio, no es el mismo tipo de certificado que se usa para firmar el xml.

**Comment by giansalex** [comment]
Tú deberías seguir trabajando con el mismo certificado registrado en sunat, o si el OSE está actuando como PSE, no creo que te proporcionen el certificado privado para firmar los XML, y sería un tipo de íntegracion con sus sistemas como se realiza con las PSE

**Comment by KhanMaytok** [comment]
Si, ya me indicaron que es con el mismo certificado
