### ISSUE TITLE
Cambio de Endpoint para trabajar con una OSE

### ISSUE THREAD

**Issue by willyk** [giansalex/greenter#82]
Hola,

Un proveedor OSE (NubeFact) nos indica o asegura que tan solo cambiando el Endpoint, user y password podemos pasar a usar su solución de OSE ya que en este caso nuestra implementación esta obligada a pasar a una OSE.

O aún mas si esta librería soporta alguna OSE

Quedo a la espera de sus comentarios, gracias.

**Comment by giansalex** [comment]
Hola, tal cual lo indica el OSE, en teoría ese debería ser el único cambio. Es decir reemplazar la URL de sunat por la que te proporcione el OSE. En el método `$see->setService('url_ose');`

**Comment by guillermofoshlen** [comment]
willyk, tienes problemas con el OSE NUBEFAC,
 Es lo que me respondieron, Lo que está ocurriendo es que los algoritmos para generar la firma en su comprobante se esté ejecutando incorrectamente, cuando me sale el error 2335
En el servidor de produccion de SUNAT no me aparece lo mismo

**Comment by sosviper** [comment]
Saludos . Yo he probado para el OSE Bizlinks  con la URL de pruebas y tengo este error:
```
object(Greenter\Model\Response\Error)#4443 (2) {
  ["code":protected]=>
  string(4) "HTTP"
  ["message":protected]=>
  string(25) "Could not connect to host"
```
Como deberia de ser el codigo. Mi codigo es:

<?php

use Greenter\See;
use Greenter\Ws\Services\SunatEndpoints;

$see = new See();
$see->setService('https://osetesting.bizlinks.com.pe/ol-ti-itcpe/billService'); // Probe tambien esta forma: https://osetesting.bizlinks.com.pe/ol-ti-itcpe/billService?wsdl
$see->setCertificate(file_get_contents(__DIR__.'/certificate.pem'));
$see->setCredentials('20327739230BIZLINKS', 'Xuvz8CUL'); // Las credenciales que me dieron

return $see;

**Comment by giansalex** [comment]
Hola @sosviper, puedes revisar este hilo #83
