### ISSUE TITLE
Could not connect to host

### ISSUE THREAD

**Issue by KhanMaytok** [giansalex/greenter#83]
Cuando quiero enviar a Bizlinks me aparece este error

    Could not connect to host

Hay algún otro ajuste que se deba hacer? Pregunto aquí porque vi un issue en el que adaptaban un cambio para bizlinks

**Comment by giansalex** [comment]
Ese es un error que también ha sucedido al conectar con Sunat, podrías ver este issue

https://github.com/giansalex/greenter/issues/54

**Comment by KhanMaytok** [comment]
Voy a revisar agregando ese campo en el constructor

**Comment by KhanMaytok** [comment]
No, aun no he tenido suerte, voy a seguir intentando soluciones

**Comment by thefantas** [comment]
Hola, yo tengo un problema similar pero ocurrió de la noche a la mañana (literalmente), desde ayer.

```
<br />
<b>Fatal error</b>:  Uncaught SoapFault exception: [WSDL] SOAP-ERROR: Parsing WSDL: Couldn't load from 'https://e-factura.sunat.gob.pe/ol-it-wsconscpegem/billConsultService?wsdl' : failed to load external entity &quot;https://e-factura.sunat.gob.pe/ol-it-wsconscpegem/billConsultService?wsdl&quot;
 in /home/user/public_html/greenter/vendor/greenter/ws/src/Ws/Services/SoapClient.php:32
Stack trace:
#0 /home/user/public_html/greenter/vendor/greenter/ws/src/Ws/Services/SoapClient.php(32): SoapClient-&gt;SoapClient('https://e-factu...', Array)
#1 /home/user/public_html/greenter/src/Util.php(91): Greenter\Ws\Services\SoapClient-&gt;__construct('https://e-factu...')
#2 /home/user/public_html/greenter/generador/factura.php(322): Util-&gt;getCdrStatusService(Array)
#3 /home/user/public_html/work/commercial/documentos_salidas/edition.php(336): require('/home/user/pu...')
#4 {main}
  thrown in <b>/home/user/public_html/greenter/vendor/greenter/ws/src/Ws/Services/SoapClient.php</b> on line <b>32</b><br />
```

**Comment by thefantas** [comment]
Tengo el mismo problema desde...

```
Wed, 10 Jul 2019 08:14:29 -0500Greenter\Model\Response\BillResult Object
(
    [cdrZip:protected] => 
    [cdrResponse:protected] => 
    [success:protected] => 
    [error:protected] => Greenter\Model\Response\Error Object
        (
            [code:protected] => HTTP
            [message:protected] => Could not connect to host
        )

)
```

**Comment by giansalex** [comment]
El motivo más frecuente en el que aparece ese mensaje, es cuando el servicio está caído. @thefantas eso no debe pasar ahora.

**Comment by thefantas** [comment]
Después de probar varias opciones entontré el problema, el detalle es que afectaba solo a mi servidor (siempre es bueno probar en otros entornos).
y solo tienen que agregar este parámetro en 
\vendor\greenter\ws\src\Ws\Services\SoapClient.php

Agregar en la línea 32
	```
	$parameters=[
			'stream_context' => stream_context_create([
				'ssl' => [
					// 'ciphers'=>'AES256-SHA',
					'verify_peer' => false,
					// 'verify_peer_name' => false,
					// 'allow_self_signed' => true
				],
			]),
		];
```

**Comment by giansalex** [comment]
Si @thefantas, sería de ayuda. He visto que la solución esta en habilitar TLS1.2 (usando `ciphers`) y/o deshabilitar la verificación del certificado.

**Comment by itamaradin15** [comment]
Justo tenia ese problema en mi vps digital ocean con ubuntu. a la final migre el sistema a un cpanel convencional y me funciono porque nunca lo pude solucionar pero creo que la solucion de @thefantas es correcta. podrias comentarme en que entorno esta tu sistema?

**Comment by thefantas** [comment]
Hola, uso Centos 7 x64, como se comenta el problema fue de hace unos días y
se corrigió deshabilitando la verificación.

Es uno sistema desarrollado desde cero y en producción.

Saludos.

**Comment by giansalex** [comment]
También se podría probar instalar/actualizar `ca-certificates`,  según la distro linux

**Comment by KhanMaytok** [comment]
Lo solucioné con lo que colocó @thefantas , muchas gracias por el aporte.
