### ISSUE TITLE
composer windows, linux, diferente!

### ISSUE THREAD

**Issue by thefantas** [giansalex/greenter#85]
Hola, buenas noches, 
Tengo una interrogante, como pueden ver en las imágenes tengo 2 copias del git, ambas con las mismas versiones y actualizadas, pero al hacer una comparación de directorios (segunda imagen) se puede apreciar inconsistencias, como en linux aparece 2 carpetas adicionales en TWIG, y quisiera saber en qué repercute eso y/o a qué se debe.

Saludos.

![imagen](https://user-images.githubusercontent.com/2816602/61155155-dc841880-a4f8-11e9-94c7-b9ece0e8eb79.png)

![imagen](https://user-images.githubusercontent.com/2816602/61155127-c9714880-a4f8-11e9-9cb7-ef33d5ca4c60.png)

**Comment by giansalex** [comment]
Hola, y es la misma versión de PHP?
Podrías eliminar el archivo `composer.lock` en ambos directorios y volver a instalar paquetes.

**Comment by thefantas** [comment]
Hola, acabo de volver a generar ambos respositorios uno con windows, el otro con linux, esta vez ambos con php 7.3.6 y lo mismo, muy extaño la verdad.

**Comment by giansalex** [comment]
Si no te genera problemas, no deberías prestarle mucha atención
