### ISSUE TITLE
Agregar placa de un auto

### ISSUE THREAD

**Issue by ADNeko** [giansalex/greenter#87]
Como podria agregar la placa de un auto al xml?

**Comment by giansalex** [comment]
Hola @ADNeko , es una factura guía remitente?

**Comment by ADNeko** [comment]
Es una factura, hay servicios que requieren placa del vehículo, lavado de auto, venta de combustible, cambio de aceite,etc. En el facturador del portal permitía poner la placa del vehículo y salia como uns especie de leyenda.

**Comment by giansalex** [comment]
Eso no puede ir en la descripción del detalle? si es como leyenda podrías colocarlo en el campo `$invoice->setObservacion('PLACA XXXXX, ....');`

**Comment by ADNeko** [comment]
Gracias

**Comment by rayo80** [comment]
Creo que aca se referia a este campo que es a nivel de item...que Sunat pide que se lo envies cuando son facturas aunque no las valida y es solo con caracter informativo
![image](https://user-images.githubusercontent.com/66443858/178025644-173cf626-f036-4869-b54e-c278d1f35f7c.png)
