### ISSUE TITLE
Impuesto a las bolsas

### ISSUE THREAD

**Issue by juanxodj** [giansalex/greenter#88]
Hola, con la nueva versión ya estás considerando el impuesto a las bolsas que hace poco se ha vuelto obligatoria?

**Comment by giansalex** [comment]
Hola @juanxodj , puedes ver el ejemplo [aqui](https://giansalex.github.io/greenter/examples/icbper/)

**Comment by byJuanjo** [comment]
Hola GianCarlos, una pregunta tengo 2 casos y en los do:

1º En una institución educativa que emite facturas y boletas exoneradas por servicios es necesario agregar tambien ese impuesto en cada uno de los documentos.

2º En otro caso de otros negocios que emiten facturas y boletas con igv normal pero no entregan bolsas tambien se tiene que agregar dicho impuesto?

**Comment by byJuanjo** [comment]
Por otro lado como se envia ese impuesto en los resumenes diarios?

**Comment by byJuanjo** [comment]
En todas las facturas del mes de agosto desde el primero me esta apareciendo este problema:

4310 - La sumatoria del Total del valor de venta m&#225;s los impuestos no concuerda con la base imponible - INFO : 4310 (nodo: "/" valor: "")

Que crees que pueda ser?

**Comment by yaircaballero10** [comment]
a mi tbn me sale lo mismo
4310 - La sumatoria del Total del valor de venta más los impuestos no concuerda con la base imponible - INFO : 4310 (nodo: "/" valor: "")

**Comment by giansalex** [comment]
Hola, si, revisando el ultimo excel de validaciones de SUNAT, faltaría agregar un campo mas: *Total precio de venta (Subtotal de la factura)*.

Acerca del resumen, existe en un nuevo campo en el detalle `setMtoIcbper`()`

**Comment by byJuanjo** [comment]
En donde se agregaria ese campo total precio venta?

Este es el ultimo XML que eh mandado pero me sigue saliendo el mismo error:

`<cac:TaxTotal>
    <cbc:TaxAmount currencyID="PEN">0.00</cbc:TaxAmount>
    <cac:TaxSubtotal>
            <cbc:TaxableAmount currencyID="PEN">198.00</cbc:TaxableAmount>
            <cbc:TaxAmount currencyID="PEN">0</cbc:TaxAmount>
            <cac:TaxCategory>
                <cac:TaxScheme>
                    <cbc:ID>9997</cbc:ID>
                    <cbc:Name>EXO</cbc:Name>
                    <cbc:TaxTypeCode>VAT</cbc:TaxTypeCode>
                </cac:TaxScheme>
            </cac:TaxCategory>
        </cac:TaxSubtotal>
    </cac:TaxTotal>
<cac:LegalMonetaryTotal>
    <cbc:LineExtensionAmount currencyID="PEN">198.00</cbc:LineExtensionAmount>
    <cbc:PayableAmount currencyID="PEN">198.00</cbc:PayableAmount>
</cac:LegalMonetaryTotal>
<cac:InvoiceLine>
    <cbc:ID>1</cbc:ID>
    <cbc:InvoicedQuantity unitCode="NIU">1</cbc:InvoicedQuantity>
    <cbc:LineExtensionAmount currencyID="PEN">198.00</cbc:LineExtensionAmount>
    <cac:PricingReference>
        <cac:AlternativeConditionPrice>
            <cbc:PriceAmount currencyID="PEN">198.000000</cbc:PriceAmount>
            <cbc:PriceTypeCode>01</cbc:PriceTypeCode>
        </cac:AlternativeConditionPrice>
        </cac:PricingReference>
    <cac:TaxTotal>
        <cbc:TaxAmount currencyID="PEN">0.00</cbc:TaxAmount>
        <cac:TaxSubtotal>
            <cbc:TaxableAmount currencyID="PEN">198.00</cbc:TaxableAmount>
            <cbc:TaxAmount currencyID="PEN">0.00</cbc:TaxAmount>
            <cac:TaxCategory>
                <cbc:Percent>18.00</cbc:Percent>
                <cbc:TaxExemptionReasonCode>20</cbc:TaxExemptionReasonCode>
                <cac:TaxScheme>
                    <cbc:ID>9997</cbc:ID>
                    <cbc:Name>EXO</cbc:Name>
                    <cbc:TaxTypeCode>VAT</cbc:TaxTypeCode>
                </cac:TaxScheme>
            </cac:TaxCategory>
        </cac:TaxSubtotal>
        </cac:TaxTotal>
    <cac:Item>
        <cbc:Description><![CDATA[Modulo=EXCEL FINANCIERO]]></cbc:Description>
        <cac:SellersItemIdentification>
            <cbc:ID>41</cbc:ID>
        </cac:SellersItemIdentification>
        </cac:Item>
    <cac:Price>
        <cbc:PriceAmount currencyID="PEN">198.000000</cbc:PriceAmount>
    </cac:Price>
</cac:InvoiceLine>
</Invoice>
`

**Comment by byJuanjo** [comment]
Cuando pongo este campo 

<cbc:TaxInclusiveAmount currencyID="PEN">9420.50</cbc:TaxInclusiveAmount>

Dentro del 
<cac:LegalMonetaryTotal>

Me devuelve este error:

object(Greenter\Model\Response\Error)#4643 (2) { ["code":protected]=> string(4) "0306" ["message":protected]=> string(476) "No se puede leer (parsear) el archivo XML - Detalle: http://xxx.xxx.xxx/ol-ti-iacpfegem/sendBill: cvc-complex-type 2.4: in element {urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2}LegalMonetaryTotal of type {urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2}MonetaryTotalType, found (in namespace urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2), but next item should be end-element" }

**Comment by giansalex** [comment]
@byJuanjo debe ir entre `<cbc:LineExtensionAmount>` y `<cbc:PayableAmount>`, ese orden puedes verlo [aqui](http://www.datypic.com/sc/ubl21/e-cac_LegalMonetaryTotal.html)

**Comment by byJuanjo** [comment]
@giansalex  jutso iba a escribir, si es tema de orden,

```
    <cac:LegalMonetaryTotal>
        <cbc:LineExtensionAmount currencyID="PEN">250.00</cbc:LineExtensionAmount>
        <cbc:TaxInclusiveAmount currencyID="PEN">250.00</cbc:TaxInclusiveAmount>
        <cbc:PayableAmount currencyID="PEN">250.00</cbc:PayableAmount>
    </cac:LegalMonetaryTotal>
```
Asi me acepto correctamente las facturas y ya no me genera el error

Por otro lado en el entorno de pruebas me las aceptaaba normal con o sin ese campo, pero en el produccion no, no me quedo de otra mas que generar facturas en el entorno de producción para hacer pruebas, tengo varias facturas por anular, mi pregunta es ese campo tambien va en las notas de credito?

**Comment by giansalex** [comment]
No esta en notas de credito/debito

**Comment by yaircaballero10** [comment]
tengo esta duda, segun este sitio:
http://wiki.facturaloperu.com/docs/fev21.html
Total valor de venta
Total precio de venta (incluye impuestos)
Monto total de descuentos del comprobante
Monto total de otros cargos del comprobante
Importe total de la venta, cesión en uso o del servicio prestado
<cac:LegalMonetaryTotal>
<cbc:LineExtensionAmount currencyID="PEN">1439.48</cbc:LineExtensionAmount>
<cbc:TaxInclusiveAmount currencyID="PEN">1698.59</cbc:TaxInclusiveAmount> // cbc:LineExtensionAmount+ IGV
<cbc:AllowanceTotalAmount currencyID="PEN">60.00</cbc:AllowanceTotalAmount>
<cbc:ChargeTotalAmount currencyID="PEN">320.00</cbc:ChargeTotalAmount>
<cbc:PrepaidAmount currencyID="PEN">100.00</cbc:PrepaidAmount>
<cbc:PayableAmount currencyID="PEN">1858.59</cbc:PayableAmount>
</cac:LegalMonetaryTotal>

**Comment by yaircaballero10** [comment]
Alguien confirma ¿? 
https://social.msdn.microsoft.com/Forums/es-ES/4b3c8b6e-5fd9-4b51-808a-b3e4dfd343e1/factura-electronica-ubl-21-sunat?forum=webdeves
```

<cac:LegalMonetaryTotal>
<!--Total Valor de Venta bruto sin aplicar descuento alguno-->
<cbc:LineExtensionAmount currencyID="PEN">11000.00</cbc:LineExtensionAmount>
<!--Total precio de venta | Valor de Venta Base - Descuento Globlales + Total Impuestos -->
<cbc:TaxInclusiveAmount currencyID="PEN">12980.00</cbc:TaxInclusiveAmount>
<!--Importe total de la venta | Total Precio Venta + Total Cargos - Total de anticipos-->
<cbc:PayableAmount currencyID="PEN">12980.00</cbc:PayableAmount>
</cac:LegalMonetaryTotal>

```

**Comment by giansalex** [comment]
Ese manual esta desfasado, puedes revisar el [excel de validaciones](http://cpe.sunat.gob.pe/node/88#item-4) de SUNAT
