### ISSUE TITLE
No e enviado resumen diario ya pasaron mas de 7 dias.

### ISSUE THREAD

**Issue by yaircaballero10** [giansalex/greenter#89]
enviar el resumen es obligatorio ¿?
tengo que hacer eso para boletas enviadas / procesadas por sunat  en primera instancia ¿?
como le doy de baja ¿?
tengo que hacer nota de credito para cancelar la boleta o lo puedo hacer directamente dándole de baja ¿?.

**Comment by giansalex** [comment]
Es un correlativo y es del resumen, es hasta 5 digitos.

**Comment by yaircaballero10** [comment]
Me sale este error:
La numeracion o nombre del documento ya ha sido enviado anteriormente - Detalle: xxx.xxx.xxx value='ticket: error: El documento: 10407269531-RC-20190818-00000002 ya fue enviado y se encuentra en estado 98; por favor espere a que se termine de procesar el envio.


no tengo numero de ticket pero en la sunat me figura esto: 

http://prntscr.com/ozcw64
https://prnt.sc/ozcvva

**Comment by quarksind** [comment]
consulta gian, como obtengo un cdr si la sunat no pudo procesar el cdr pero aceptó el xml normal, me tocó con 1 boleta y 1 factura el resto esta perfecto... espero tu respuesta

**Comment by giansalex** [comment]
Hola @quarksind, para el caso de Boleta, puedes revisarlo en el portal de Sunat, y en el caso de factura, existe el servicio para consultar cdr. https://greenter-sample.herokuapp.com/examples/pages/status-cdr.php

**Comment by p3dr0tg** [comment]
@yaircaballero10 cuando esta en estado 98 solo tienes que consultar el ticket ya no enviarlo de nuevo;
cuando envias resumen a sunat te devuelve un numero de ticket y con ese numero consultas para que te devuelva el cdr

**Comment by abelnexus** [comment]
@p3dr0tg como haces esa consulta ? que codigo usas o donde lo haces

**Comment by MrJmpl3** [comment]
> @p3dr0tg como haces esa consulta ? que codigo usas o donde lo haces

En el manual de la SUNAT esta claramente como hacer la consulta del ticket.

**Comment by giansalex** [comment]
Este es el método que puedes utilizar https://github.com/giansalex/greenter-sample/blob/master/examples/resumen.php#L86

**Comment by anthonybaquerizo** [comment]
Hola alguien actualmente esta teniendo problemas con el servicio de consulta de CDR SUNAT.
Ruta: https://www.sunat.gob.pe/ol-it-wsconscpegem/billConsultService?wsdl
