### ISSUE TITLE
 No tiene el perfil para enviar comprobantes electronicos 

### ISSUE THREAD

**Issue by byJuanjo** [giansalex/greenter#92]
Alguien mas tiene problemas con este error, veo en varios foros de facebook que se les esta presentando el problema a clientes aleatoriamente

0111 - No tiene el perfil para enviar comprobantes electronicos - Detalle: value='ticket: 7e88e9da-e69d-422f-8fa8-ca5837fa3de9, error: INFO: (nodo: "" valor: "")'

**Comment by giansalex** [comment]
Hola @byJuanjo, puedes probar cambiando la url del servicio a `https://www.sunat.gob.pe/ol-ti-itcpfegem/billService`, eso le indico sunat a alguien con el mismo problema.
