### ISSUE TITLE
no se puede enviar el resumen diario por nada

### ISSUE THREAD

**Issue by abelnexus** [giansalex/greenter#93]
buenas tardes, desde este mes practicamente no envia ni un resumen diario
siempre que envio se queda cargando y retorna null. y al enviarlo nuevamente me indica esto:
Error: 2223 - El archivo ya fue presentado anteriormente - Detalle: value='ticket: fb771fbc-b956-4657-91fa-322c7e10da6f, error: INFO: (nodo: "/SummaryDocuments/cbc:ID" valor: "20191018-104")
con el ticket consulto el estado y me indica que no existe el numero de ticket.
que se puede hacer en este caso ya que resulta imposible obtener el cdr y tampoco aparece en el portal de sunat las boletas :( 
le aumento un numero al correlativo de los resumenes diarios y se vuelve a repetir lo ya mencionado

**Comment by giansalex** [comment]
Hola Abel, podrías colocar log en la respuesta del servicio, o algún error que no se está mostrando. Esto parece ser a nivel de la aplicación, y no de la librería en si.

**Comment by abelnexus** [comment]
hola gian carlos, uso este codigo para consultar el ticket:

                                                // Envio a SUNAT.
                                              
                                              $see = $util->getSee(SunatEndpoints::FE_PRODUCCION);
                                              $res = $see->getStatus("300000002544168");
                                              //$res = $see->send($sum);
                                              $util->writeXml($sum, $see->getFactory()->getLastXml());
                                              $pdf = $util->getPdf($sum);
                                              $util->showPdf($pdf, $sum->getName().'.pdf'); 
                                              if (!$res->isSuccess()) {
                                                 echo $util->getErrorResponse($res->getError());
                                                 return;
                                              }
                                              
                                              /**@var $res \Greenter\Model\Response\SummaryResult*/
                                              //$ticket = $res->getTicket();
                                              //echo 'Ticket :<strong>' . $ticket .'</strong>';
                                              
                                              
                                              if (!$res->isSuccess()) {
                                                  echo $util->getErrorResponse($res->getError());
                                                   return;
                                              }
                                              
                                              $cdr = $res->getCdrResponse();
                                              $util->writeCdr($sum, $res->getCdrZip());

y me sale esto:

<br />
<b>Notice</b>:  Undefined property: stdClass::$content in <b>C:\xampp\htdocs\arkialum\vendor\greenter\ws\src\Ws\Services\ExtService.php</b> on line <b>35</b><br />
<br />
<b>Fatal error</b>:  Uncaught TypeError: Argument 1 passed to Util::getResponseFromCdr() must be an instance of Greenter\Model\Response\CdrResponse, null given, called in C:\xampp\htdocs\arkialum\controllers\resumen_diario.php on line 177 and defined in C:\xampp\htdocs\arkialum\src\Util.php:54
Stack trace:
#0 C:\xampp\htdocs\arkialum\controllers\resumen_diario.php(177): Util-&gt;getResponseFromCdr(NULL)
#1 C:\xampp\htdocs\arkialum\aplication\Bootstrap.php(90): Resumen_diario-&gt;registrar_resumen()
#2 C:\xampp\htdocs\arkialum\aplication\Bootstrap.php(20): Bootstrap-&gt;callControllerMethod()
#3 C:\xampp\htdocs\arkialum\index.php(20): Bootstrap-&gt;init()
#4 {main}
  thrown in <b>C:\xampp\htdocs\arkialum\src\Util.php</b> on line <b>54</b><br />

**Comment by abelnexus** [comment]
hay algunas imcopatibilidades con el nuevo codigo de "greenter-sample" debido a que uso el antiguo codigo, pero solo quiero obtener el cdr

**Comment by giansalex** [comment]
Tal vez primero deberias validar que el valor de `$result->getCdrResponse())`, sea diferente de null, y esto probablemente se debe a que `$result->getCode()`, que indica el estado del procesamiento del resumen tenga valor **98 (En proceso)**, y el cdr aun no esta disponible

**Comment by abelnexus** [comment]
es normal que dure tantos dias ?
["code":protected]=>
  string(2) "98"
  ["cdrZip":protected]=>
  NULL
  ["cdrResponse":protected]=>
  NULL
  ["success":protected]=>
  bool(true)
  ["error":protected]=>
  NULL

**Comment by giansalex** [comment]
No deberia demorar esa cantidad de tiempo, deberías informar a SUNAT
