### ISSUE TITLE
In BillSender.php line 37: Trying to get property of non-object 

### ISSUE THREAD

**Issue by AnthonyLJ96** [giansalex/greenter#95]
Hola @giansalex , al enviar múltiples facturas seguidas obtengo este error. A qué se puede deber?. Gracias de antemano.

**Comment by giansalex** [comment]
Parece que el servicio de sunat no esta devolviendo la respuesta correcta, o que url del servicio estas usando?

**Comment by AnthonyLJ96** [comment]
https://e-factura.sunat.gob.pe/ol-ti-itcpfegem/billService

Está dentro de la librería. Eso no sucede siempre.

**Comment by AnthonyLJ96** [comment]
Me volvió a suceder algo similar pero de otro archivo.
 Trying to get property of non-object, Code: 0 BASE_PATH/vendor/greenter/ws/src/Ws/Services/ExtService.php, Line: 43

Quizás debería haber un try catch en la librería para esos y retornar un status de que no consiguió conectarse con sunat para poder manejar un reenvío de documentos.

**Comment by giansalex** [comment]
Hola @AnthonyLJ96 , para este caso no funcionará el try-catch, ya que no es una excepción. Tendrías que registrar un `set_error_handler`.  
Aunque lo mejor será validar la existencia de los campos con los que se necesita trabajar.

**Comment by giansalex** [comment]
@AnthonyLJ96 agregue una validación cuando la respuesta no sea la especificada en el servicio de sunat, de esta forma puedes utilizar un try-catch para manejar ese escenario.

https://github.com/giansalex/greenter-ws/commit/469e6c22b75db3eeda674e2c056e8cbc81d8bdf2

**Comment by megasoft-dev** [comment]
Hola mi estimado, tengo un error que empezó el día de hoy:
Trying to get property 'data' of non-object
exactamente en ésta línea de la clase
vendor/giansalex/peru-consult/src/Peru/Jne/Dni.php:59

`public function get(string $dni): ?Person

    {
        $url = self::URL_CONSULT;
        $json = $this->client->post(
            $url,
            json_encode(['CODDNI' => $dni]),
            [
                'Content-Type' => 'application/json;chartset=utf-8',
                'Requestverificationtoken' => '30OB7qfO2MmL2Kcr1z4S0ttQcQpxH9pDUlZnkJPVgUhZOGBuSbGU4qM83JcSu7DZpZw-IIIfaDZgZ4vDbwE5-L9EPoBIHOOC1aSPi4FS_Sc1:clDOiaq7mKcLTK9YBVGt2R3spEU8LhtXEe_n5VG5VLPfG9UkAQfjL_WT9ZDmCCqtJypoTD26ikncynlMn8fPz_F_Y88WFu

            ]);
        $raw = json_decode($json)->data;
        return $this->parser->parse($dni, $raw);
    }
`

**Comment by giansalex** [comment]
Hola @megasoft-dev , eso pertenece a otro repositorio, podrías crear el issue en https://github.com/giansalex/peru-consult

**Comment by megasoft-dev** [comment]
> Hola @megasoft-dev , eso pertenece a otro repositorio, podrías crear el issue en https://github.com/giansalex/peru-consult

Si, disculpa me confundí entre líneas... xD
