### ISSUE TITLE
object(Greenter\Model\Response\Error)#4776 (2) { ["code":protected]=> string(4) "0151" ["message":protected]=> string(161) "El nombre del archivo ZIP es incorrecto - Detalle: xxx.xxx.xxx value='ticket: 1574108632776 error: Validation ZIP Filename error: XXXXXXXXXXX-01-01-00000002.zip'" }

### ISSUE THREAD

**Issue by jose1894** [giansalex/greenter#96]
Configure todo, lo probe como aparece en la pagina de greenter, pero cuando seteo los valores reales y hago el envio al servidor de pruebas me aparece el siguiente error:

object(Greenter\Model\Response\Error)#4776 (2) { ["code":protected]=> string(4) "0151" ["message":protected]=> string(161) "El nombre del archivo ZIP es incorrecto - Detalle: xxx.xxx.xxx value='ticket: 1574108632776 error: Validation ZIP Filename error: XXXXXXXXXXX-01-01-00000002.zip'" }

**Comment by giansalex** [comment]
Parece que el problema en `XXXXXXXXXXX-01-01-00000002.zip`, es la serie del comprobante; debería ser `F001`

**Comment by jose1894** [comment]
Excelente, gracias por su pronta respuesta
Ahora obtengo el siguiente error:

object(Greenter\Model\Response\Error)#4785 (2) { ["code":protected]=> string(4) "0306" ["message":protected]=> string(335) "No se puede leer (parsear) el archivo XML - Detalle: http://xxx.xxx.xxx/ol-ti-itcpfegem-beta/billService: cvc-simple-type 1: element {urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2}InvoicedQuantity of type {urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2}InvoicedQuantityType may not be empty" }

Este es mi codigo para cargar el detalle

        $item[$key] = (new SaleDetail())
            ->setCodProducto($value->productoPdetalle->cod_prod)
            ->setUnidad($value->productoPdetalle->umedProd->sunatm_und)
            ->setCantidad($value->cant_pdetalle)
            ->setDescripcion($value->productoPdetalle->des_prod)
            ->setMtoBaseIgv($totalSIGV) //Total por item sin IGV
            ->setPorcentajeIgv($value->impuesto_pdetalle) // 18%
            ->setIgv($totalIGV) //Total de IGV por item
            ->setTipAfeIgv('10')
            ->setTotalImpuestos($totalIGV)
            ->setMtoValorVenta($totalIGV)
            ->setMtoValorUnitario($precioUnitarioSIGV)
            ->setMtoPrecioUnitario($value->precio_pdetalle);

**Comment by giansalex** [comment]
Revisa que la cantidad (`$value->cant_pdetalle`) tenga valor, y se un numero valido

**Comment by jose1894** [comment]
Hice un print del arreglo y me muestra lo siguiente:

![image](https://user-images.githubusercontent.com/12040206/69096419-62255100-0a22-11ea-9ce6-11605fe34c21.png)

**Comment by jose1894** [comment]
Corregido, me faltaba un decimal a la cantidad

**Comment by jose1894** [comment]
falsa alarma, sigue el error

**Comment by giansalex** [comment]
Podrias hacer un `var_dump($arreglo)`

**Comment by jose1894** [comment]
![image](https://user-images.githubusercontent.com/12040206/69099489-d95de380-0a28-11ea-874f-f147bf67a3b2.png)
![image](https://user-images.githubusercontent.com/12040206/69099535-f4305800-0a28-11ea-8ba6-e1d82194fd9a.png)

**Comment by giansalex** [comment]
Si te sigue saliendo error en `InvoicedQuantity`, intenta setear `->setCantidad(floatval($value->cant_pdetalle))`

**Comment by jose1894** [comment]
Ya lo seteé, pero continua el error, el error es "InvoicedQuantityType may not be empty"

**Comment by giansalex** [comment]
Si puedes guardar el XML, debería haber un valor aqui
![image](https://user-images.githubusercontent.com/14926587/69157233-ab24e600-0ab2-11ea-8635-fab8847dbf19.png)

**Comment by jose1894** [comment]
Mi error fue el siguiente: 

$invoice->setDetails([$item]);

Dejar $item dentro de un arreglo, me di cuenta y solo coloque:

$invoice->setDetails($item) 

Y me funcionó, por el momento sigo con las pruebas... Y muchas gracias por tu ayuda

![image](https://user-images.githubusercontent.com/12040206/69178364-711a0b00-0ad7-11ea-8f75-a3fdffe97522.png)

**Comment by jose1894** [comment]
Mi error fue el siguiente:

$invoice->setDetails([$item]);

Dejar $item dentro de un arreglo, me di cuenta y solo coloque:

$invoice->setDetails($item)

Y me funcionó, por el momento sigo con las pruebas... Y muchas gracias por tu ayuda

![image](https://user-images.githubusercontent.com/12040206/69178587-e84f9f00-0ad7-11ea-8878-0e537ce773b3.png)
