### ISSUE TITLE
El nombre del archivo ZIP es incorrecto - Detalle: xxx.xxx.xxx value='ticket:  error: Error de nombre archivo ".zip codigo cpe:  no es un cpe valido'

### ISSUE THREAD

**Issue by AnthonyLJ96** [giansalex/greenter#98]
Buenos días @giansalex , obtengo el siguiente error con dos facturas.  A qué se puede deber?

**Comment by giansalex** [comment]
Hola @AnthonyLJ96 la ultima vez que vi eso fue porque el tipo de documento no tenia los 2 digitos
.
