### ISSUE TITLE
SUNAT Error code: 4294

### ISSUE THREAD

**Issue by jose1894** [giansalex/greenter#99]
Buenas tardes, 

He generado las facturas perfectamente, las envío y la SUNAT me responde como comprobante aceptado, pero luego de un tiempo me di cuenta que en el retorno me muestra este error:

![image](https://user-images.githubusercontent.com/12040206/74278916-f46a8780-4ce7-11ea-909f-eeaa9accd861.png)

Muy agradecido por la ayuda que me pueda brindar

**Comment by giansalex** [comment]
Hola @jose1894, estas enviando información en el campo `setMtoBaseIgv` del detalle?    
[Ejemplo](https://github.com/giansalex/greenter-sample/blob/master/examples/factura.php#L40)

**Comment by jose1894** [comment]
Hola @giansalex, si por supuesto:

![image](https://user-images.githubusercontent.com/12040206/74282308-e6b80080-4ced-11ea-8d77-076996868c59.png)

**Comment by jose1894** [comment]
Reenvío:

![image](https://user-images.githubusercontent.com/12040206/74282432-1ff07080-4cee-11ea-90a5-b9202fcf0244.png)

**Comment by giansalex** [comment]
Si tienes un XML de esas facturas, podrías enviarlo a mi correo.

**Comment by jose1894** [comment]
Indicame tu correo por favor

**Comment by jose1894** [comment]
Listo ya lo tengo

**Comment by giansalex** [comment]
He visto varias cosas que no estoy seguro de donde salen.
![image](https://user-images.githubusercontent.com/14926587/74285835-9e501100-4cf4-11ea-9a40-9fe5409c84e0.png)

Por ejemplo el precio con igv, no se relaciona con el valor unitario. El `valor venta` deberia ser el producto de `Cantidad * Valor unitario` (podría ser diferente si hubiese descuentos).
Pero especificamente el codigo de error  `4294` esta relacionado con el monto que esta subrayado en rojo, que este contexto deberia ser igual al `valor venta`.

**Comment by jose1894** [comment]
Hmmm... Bueno revisaré nuevamente y te comento lo que consiga en el camino

**Comment by jose1894** [comment]
Hola buenas tardes,

Si el problema es el descuento, debo entonces aplicar esto:

[image: image.png]

**Comment by giansalex** [comment]
Si, recuerda que el Monto base deberia ser igual al valor del `Valor venta + ISC (si lo hubiera)`

**Comment by jose1894** [comment]
Buenas tardes, disculpa que no respondí antes, me trasladaron de sitio de
trabajo, por eso no segui con la depuración, pero en lo que regrese y tenga
oportunidad continuo.

Muchas gracias, y disculpa la molestia
